import { useState, useEffect, useRef, useLayoutEffect } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { pagesAPI, worksAPI } from '@/services/api';
import useWindowSize from '@/hooks/useWindowSize';
import vectorIcon from '@/assets/Vector.png';
import EditableSection from '@/components/EditableSection';
import heroDecor1 from '@/assets/Group 37369.png';
import heroDecor2 from '@/assets/Group 37368.png';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

// Register GSAP plugin
gsap.registerPlugin(ScrollTrigger);

// Helper to get full image URL
const getImageUrl = (path) => {
  if (!path) return '';
  if (path.startsWith('http')) return path;
  const baseUrl = import.meta.env.VITE_API_URL || '';
  return `${baseUrl}${path}`;
};

const Home = () => {
  const { isMobile, isTablet } = useWindowSize();
  const [searchParams] = useSearchParams();
  const isEditorMode = searchParams.get('editor') === 'true';
  const [selectedSection, setSelectedSection] = useState(null);
  const [expandedAccordion, setExpandedAccordion] = useState(0);
  const [expandedFaq, setExpandedFaq] = useState(null);
  const [currentServiceIndex, setCurrentServiceIndex] = useState(0);
  const [works, setWorks] = useState([]);

  // Refs for GSAP animation
  const heroSectionRef = useRef(null);
  const heroImageRef = useRef(null);
  const animatedImageRef = useRef(null);
  const targetSectionRef = useRef(null);
  const animationRef = useRef(null);

  // Page content from CMS
  const [pageContent, setPageContent] = useState({
    // Hero Section
    heroImage: '',
    heroImageMobile: '',
    heroDescription: 'We are UX/UI agency helping ambitious companies and visionary entrepreneurs bring the next design revolution.',
    heroButton1Text: 'Schedule Call',
    heroButton2Text: 'Our Work',
    heroInstantText: 'Get instant response',
    // Partner Brands Section
    partnerTitle: 'Our partner brands have built their tribe and strong presence in the market',
    partnerLogos: [],
    // Experience Section
    experienceTitle1: "You've",
    experienceTitle2: 'already experienced it.',
    experienceTitle3: 'You',
    experienceTitle4: "just didn't notice.",
    experienceDescription: 'We are UX/UI agency helping ambitious companies and visionary entrepreneurs bring the next design revolution.',
    // Projects Section
    projectsSectionTitle: 'Featured Projects',
    // Want To See More
    wantMoreTitle: 'Want To See More?',
    wantMoreButtonText: 'View All Case Studies',
    // Real Numbers Section
    realNumbersTitle: 'Real Numbers.',
    realNumbersTitleNormal: 'Real Impacts',
    stat1Value: '$280,366',
    stat1Label: 'Total Revenue Generated by our clients',
    stat2Value: '261+',
    stat2Label: 'Stores Launched and counting',
    stat3Value: '5.8%',
    stat3Label: 'Average Conversion Rate vs 2.5% industry avg',
    stat4Value: '4.8/5',
    stat4Label: 'Client Satisfaction from 200+ reviews',
    stat5Value: '1,247+',
    stat5Label: 'Design revisions survived',
    stat5Image: '',
    // Services Section
    servicesTitle: 'Turning',
    servicesTitleNormal: 'Brand, Product, and Tech Into One Experience',
    service1Title: 'Research & Strategy',
    service1Description: 'Data and Insights are backbone of building successful products. We ensure laying a perspective that balances business objectives and customer expectations.',
    service1Image: '',
    service2Title: 'Development',
    service2Description: 'Data and Insights are backbone of building successful products. We ensure laying a perspective that balances business objectives and customer expectations.',
    service2Image: '',
    service3Title: 'Designing',
    service3Description: 'Data and Insights are backbone of building successful products. We ensure laying a perspective that balances business objectives and customer expectations.',
    service3Image: '',
    // CTA Button (mid page)
    ctaMidButtonText: 'Schedule Call',
    ctaMidInstantText: 'Get instant response',
    // Brands Section
    brandsTitle: "Brands don't",
    brandsTitleItalic: 'grow',
    brandsTitleEnd: 'by accident.',
    brandsDescription: 'Most get lost in the noise. We combine strategy, design, and clarity to turn ideas into brands people choose — and remember.',
    accordion1Title: 'See What Others Miss',
    accordion1Items: 'UX audit,Data Analysis,Marketing and Research,Information Architecture',
    accordion2Title: 'Shape What Matters',
    accordion2Items: '',
    accordion3Title: 'Craft What Converts',
    accordion3Items: '',
    accordion4Title: 'Scale What Works',
    accordion4Items: '',
    // CTA Section (bottom)
    ctaHeading: 'Your search for agency ends here...',
    ctaDescription1: 'We combine strategy, design, and performance to create',
    ctaDescription2: 'experiences that convert.',
    ctaDescription3: "Let's build something that moves the needle.",
    ctaButtonText: 'Schedule Call',
    ctaInstantText: 'Get instant response',
    // FAQ Section
    faqTitle: 'Frequently',
    faqTitleNormal: 'asked question',
    faq1Question: 'Lorem ipsum dolor sit amet consectetur?',
    faq1Answer: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    faq2Question: 'Lorem ipsum dolor sit amet consectetur?',
    faq2Answer: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    faq3Question: 'Lorem ipsum dolor sit amet consectetur?',
    faq3Answer: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    faq4Question: 'Lorem ipsum dolor sit amet consectetur?',
    faq4Answer: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    faq5Question: 'Lorem ipsum dolor sit amet consectetur?',
    faq5Answer: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    faqContactText: "Any more questions, we'll be happy to answer.",
    faqContactLink: 'CONTACT US',
    // Section Visibility (default all visible)
    heroVisible: true,
    partnersVisible: true,
    experienceVisible: true,
    projectsVisible: true,
    wantMoreVisible: true,
    realNumbersVisible: true,
    servicesVisible: true,
    brandsVisible: true,
    ctaVisible: true,
    faqVisible: true,
  });

  // Helper to check if section is visible
  const isSectionVisible = (sectionId) => {
    const visibilityKey = `${sectionId}Visible`;
    return pageContent[visibilityKey] !== false;
  };

  // Helper to check if section should be rendered (always render in editor mode)
  const shouldRenderSection = (sectionId) => {
    if (isEditorMode) return true; // Always render in editor mode (will show blurred if hidden)
    return isSectionVisible(sectionId);
  };

  // Helper to check if section is hidden (for blur effect)
  const isSectionHidden = (sectionId) => {
    return !isSectionVisible(sectionId);
  };

  // Testimonial data from About page
  const [testimonialData, setTestimonialData] = useState({
    clientLabelItalic: 'Look',
    clientLabelNormal: 'what our client said..',
    testimonialQuote1: 'Lorem ipsum dolor sit amet consectetur. Ullamcorper amet arcu quis elementum. Convallis purus mauris at in.',
    testimonialQuote2: 'Pretium pharetra aliquam consequat duis ac risus vitae sollicitudin pharetra.',
    testimonialAuthor: 'Reema Roy',
    testimonialRole: 'Head of Marketing, Company-name',
    testimonialImage: '',
    testimonialStats: [
      { value: '+45%', label: 'AOV (Average Order Value)' },
      { value: '+24%', label: 'CTR (Click-through rate)' },
      { value: '+16%', label: 'Return-rate per customer' },
    ],
  });

  useEffect(() => {
    fetchPageContent();
    fetchTestimonialData();
    fetchWorks();
  }, []);

  // Editor mode: Listen for updates from parent
  useEffect(() => {
    if (!isEditorMode) return;

    const handleMessage = (event) => {
      if (event.origin !== window.location.origin) return;

      if (event.data.type === 'EDITOR_UPDATE' || event.data.type === 'EDITOR_INIT') {
        if (event.data.payload?.data) {
          setPageContent(prev => ({
            ...prev,
            ...event.data.payload.data
          }));
        }
      }

      if (event.data.type === 'SECTION_SELECTED') {
        setSelectedSection(event.data.sectionId);
      }
    };

    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
  }, [isEditorMode]);


  const fetchPageContent = async () => {
    try {
      const response = await pagesAPI.getOne('home');
      if (response.data.data?.content) {
        setPageContent(prev => ({ ...prev, ...response.data.data.content }));
      }
    } catch (error) {
      console.log('Using default content for home page');
    }
  };

  const fetchTestimonialData = async () => {
    try {
      const response = await pagesAPI.getOne('about');
      if (response.data.data?.content) {
        const aboutContent = response.data.data.content;
        setTestimonialData(prev => ({
          ...prev,
          clientLabelItalic: aboutContent.clientLabelItalic || prev.clientLabelItalic,
          clientLabelNormal: aboutContent.clientLabelNormal || prev.clientLabelNormal,
          testimonialQuote1: aboutContent.testimonialQuote1 || prev.testimonialQuote1,
          testimonialQuote2: aboutContent.testimonialQuote2 || prev.testimonialQuote2,
          testimonialAuthor: aboutContent.testimonialAuthor || prev.testimonialAuthor,
          testimonialRole: aboutContent.testimonialRole || prev.testimonialRole,
          testimonialImage: aboutContent.testimonialImage || prev.testimonialImage,
        }));
      }
    } catch (error) {
      console.log('Using default testimonial content');
    }
  };

  const fetchWorks = async () => {
    try {
      const response = await worksAPI.getAll({ published: true });
      setWorks(response.data.data.slice(0, 3)); // Get first 3 projects
    } catch (error) {
      console.error('Error fetching works:', error);
    }
  };

  // Partner logos - fetched from admin
  const partnerLogosDesktop = pageContent.partnerLogos || [];
  const partnerLogosMobile = pageContent.partnerLogosMobile || [];
  const partnerLogos = isMobile ? partnerLogosMobile : partnerLogosDesktop;

  // Fallback text logos if no images uploaded
  const fallbackLogos = [
    'AUTOMATTIC', 'Wealthsimple', 'SPACEX', 'gusto', 'attentive', 'SONY',
    'Square', 'dribbble', 'drips', 'Dropbox'
  ];

  // Services data
  const services = [
    { title: pageContent.service1Title, description: pageContent.service1Description, image: pageContent.service1Image },
    { title: pageContent.service2Title, description: pageContent.service2Description, image: pageContent.service2Image },
    { title: pageContent.service3Title, description: pageContent.service3Description, image: pageContent.service3Image },
  ];

  // Accordion items for Brands section
  const accordionItems = [
    { title: pageContent.accordion1Title, items: pageContent.accordion1Items?.split(',').map(i => i.trim()).filter(i => i) || [] },
    { title: pageContent.accordion2Title, items: pageContent.accordion2Items?.split(',').map(i => i.trim()).filter(i => i) || [] },
    { title: pageContent.accordion3Title, items: pageContent.accordion3Items?.split(',').map(i => i.trim()).filter(i => i) || [] },
    { title: pageContent.accordion4Title, items: pageContent.accordion4Items?.split(',').map(i => i.trim()).filter(i => i) || [] },
  ];

  // FAQ items
  const faqItems = [
    { question: pageContent.faq1Question, answer: pageContent.faq1Answer },
    { question: pageContent.faq2Question, answer: pageContent.faq2Answer },
    { question: pageContent.faq3Question, answer: pageContent.faq3Answer },
    { question: pageContent.faq4Question, answer: pageContent.faq4Answer },
    { question: pageContent.faq5Question, answer: pageContent.faq5Answer },
  ];

  // Project colors
  const projectColors = ['#D2F34C', '#2558BF', '#E2775A'];

  // GSAP ScrollTrigger Animation for hero image (works on both mobile and desktop)
  useLayoutEffect(() => {
    if (!animatedImageRef.current || !heroSectionRef.current || !targetSectionRef.current) return;

    const inlineImage = heroImageRef.current;
    if (!inlineImage) return;

    const initAnimation = () => {
      const heroSection = heroSectionRef.current;
      const animatedImage = animatedImageRef.current;
      const targetSection = targetSectionRef.current;
      const targetImg = targetSection.querySelector('img');
      const viewportWidth = window.innerWidth;
      const isMobileView = viewportWidth <= 768;

      // Get measurements
      const inlineRect = inlineImage.getBoundingClientRect();

      // Starting values (inline pill position) - different for mobile/desktop
      const startLeft = inlineRect.left;
      const startTop = inlineRect.top;
      const startWidth = isMobileView ? 57 : 125;
      const startHeight = isMobileView ? 43 : 67;
      const startRadius = 300;

      // Ending values (full width, positioned at top of viewport when hero scrolls out)
      const endLeft = 0;
      const endTop = 0;
      const endWidth = viewportWidth;
      const endHeight = isMobileView ? 792 : 832;
      const endRadius = 0;

      // Hide target image initially
      if (targetImg) targetImg.style.opacity = '0';

      // Set initial state
      gsap.set(animatedImage, {
        position: 'fixed',
        left: startLeft,
        top: startTop,
        width: startWidth,
        height: startHeight,
        borderRadius: startRadius,
        opacity: 0,
        zIndex: 999,
      });

      // Create scroll-linked animation
      ScrollTrigger.create({
        trigger: heroSection,
        start: 'top top',
        end: 'bottom top',
        scrub: 0,
        onUpdate: (self) => {
          const progress = self.progress;

          // Hide inline image after small scroll
          inlineImage.style.opacity = progress > 0.02 ? '0' : '1';

          // Show/hide animated image
          if (progress > 0.01 && progress < 0.99) {
            animatedImage.style.opacity = '1';
          } else if (progress <= 0.01) {
            animatedImage.style.opacity = '0';
          }

          // Smooth interpolation using eased progress for natural feel
          const easedProgress = progress < 0.5
            ? 2 * progress * progress
            : 1 - Math.pow(-2 * progress + 2, 2) / 2;

          // Interpolate all values
          const currentWidth = startWidth + (endWidth - startWidth) * easedProgress;
          const currentHeight = startHeight + (endHeight - startHeight) * easedProgress;
          const currentRadius = startRadius + (endRadius - startRadius) * easedProgress;

          // Position: start from inline, end at top-left (0,0)
          const currentLeft = startLeft + (endLeft - startLeft) * easedProgress;
          const currentTop = startTop + (endTop - startTop) * easedProgress;

          // Apply interpolated values
          animatedImage.style.width = `${currentWidth}px`;
          animatedImage.style.height = `${currentHeight}px`;
          animatedImage.style.left = `${currentLeft}px`;
          animatedImage.style.top = `${currentTop}px`;
          animatedImage.style.borderRadius = `${currentRadius}px`;

          // At end, swap to static image
          if (progress >= 0.99) {
            animatedImage.style.opacity = '0';
            if (targetImg) targetImg.style.opacity = '1';
          } else {
            if (targetImg) targetImg.style.opacity = '0';
          }
        },
      });
    };

    const timer = setTimeout(initAnimation, 100);

    return () => {
      clearTimeout(timer);
      ScrollTrigger.getAll().forEach(trigger => trigger.kill());
    };
  }, [isMobile, pageContent.heroImage]);

  // Refresh ScrollTrigger on resize
  useEffect(() => {
    const handleResize = () => {
      ScrollTrigger.refresh();
    };
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  return (
    <div style={{ minHeight: '100vh', backgroundColor: '#fff', fontFamily: "'Plus Jakarta Sans', 'Inter', sans-serif", overflowX: 'hidden' }}>

      {/* Animated Hero Image - GSAP controlled (works on both mobile and desktop) */}
      {(pageContent.heroImage || pageContent.heroImageMobile) && (
        <div
          ref={animatedImageRef}
          style={{
            position: 'fixed',
            width: isMobile ? '57px' : '125px',
            height: isMobile ? '43px' : '67px',
            borderRadius: '300px',
            overflow: 'hidden',
            zIndex: 999,
            opacity: 0,
            pointerEvents: 'none',
            willChange: 'transform, width, height, left, top, border-radius',
          }}
        >
          <img
            src={getImageUrl(isMobile ? (pageContent.heroImageMobile || pageContent.heroImage) : pageContent.heroImage)}
            alt=""
            style={{
              width: '100%',
              height: '100%',
              objectFit: 'cover',
            }}
          />
        </div>
      )}

      {/* Hero Section - Blue with Green Circles */}
      {shouldRenderSection('hero') && (
      <EditableSection sectionId="hero" label="Hero Section" isEditorMode={isEditorMode} isSelected={selectedSection === 'hero'} isHidden={isSectionHidden('hero')}>
        <section
          ref={heroSectionRef}
          style={{
            width: '100%',
            minHeight: isMobile ? '609px' : isTablet ? '600px' : '700px',
            backgroundColor: '#2558BF',
            position: 'relative',
            overflow: 'hidden',
            padding: isMobile ? '77px 0 80px' : isTablet ? '80px 40px 100px' : '100px 100px 120px',
          }}>
          {/* Decorative Green Circles - Desktop only */}
          {!isMobile && (
            <>
              {/* Left Column - Half visible (50% inside) */}
              <div style={{ position: 'absolute', top: '50px', left: '-92px', width: '185px', height: '185px', borderRadius: '50%', backgroundColor: '#AAD28E' }} />
              <div style={{ position: 'absolute', top: '260px', left: '-92px', width: '185px', height: '185px', borderRadius: '50%', backgroundColor: '#AAD28E' }} />
              <div style={{ position: 'absolute', top: '470px', left: '-92px', width: '185px', height: '185px', borderRadius: '50%', backgroundColor: '#AAD28E' }} />
              {/* Bottom-Left Corner - partial visible */}
              <div style={{ position: 'absolute', bottom: '-92px', left: '-92px', width: '185px', height: '185px', borderRadius: '50%', backgroundColor: '#AAD28E' }} />
              {/* Right Side - Full circles in middle + 1/4 visible on edge */}
              <div style={{ position: 'absolute', top: '0px', right: '-139px', width: '185px', height: '185px', borderRadius: '50%', backgroundColor: '#AAD28E' }} />
              {/* Full circles on right side */}
              <div style={{ position: 'absolute', top: '530px', right: '430px', width: '185px', height: '185px', borderRadius: '50%', backgroundColor: '#AAD28E' }} />
              <div style={{ position: 'absolute', top: '330px', right: '100px', width: '185px', height: '185px', borderRadius: '50%', backgroundColor: '#AAD28E' }} />
              <div style={{ position: 'absolute', top: '210px', right: '-139px', width: '185px', height: '185px', borderRadius: '50%', backgroundColor: '#AAD28E' }} />
              <div style={{ position: 'absolute', top: '420px', right: '-139px', width: '185px', height: '185px', borderRadius: '50%', backgroundColor: '#AAD28E' }} />
              {/* Bottom Row - 1/4 visible (25% inside) */}
              <div style={{ position: 'absolute', bottom: '-139px', left: '150px', width: '185px', height: '185px', borderRadius: '50%', backgroundColor: '#AAD28E' }} />
              <div style={{ position: 'absolute', bottom: '-139px', left: '400px', width: '185px', height: '185px', borderRadius: '50%', backgroundColor: '#AAD28E' }} />
              <div style={{ position: 'absolute', bottom: '-139px', left: '650px', width: '185px', height: '185px', borderRadius: '50%', backgroundColor: '#AAD28E' }} />
              <div style={{ position: 'absolute', bottom: '-139px', right: '300px', width: '185px', height: '185px', borderRadius: '50%', backgroundColor: '#AAD28E' }} />
              <div style={{ position: 'absolute', bottom: '-139px', right: '50px', width: '185px', height: '185px', borderRadius: '50%', backgroundColor: '#AAD28E' }} />
              {/* Bottom-Right Corner - only 50px visible */}
              <div style={{ position: 'absolute', bottom: '-85px', right: '-135px', width: '185px', height: '185px', borderRadius: '50%', backgroundColor: '#AAD28E' }} />
            </>
          )}

          {/* Hero Content */}
          <div style={{
            position: 'relative',
            zIndex: 1,
            maxWidth: isMobile ? '100%' : '900px',
            paddingTop: isMobile ? '68px' : '80px',
            marginLeft: isMobile ? '0' : '98px',
            textAlign: isMobile ? 'center' : 'left',
          }}>
            {/* Main Title */}
            <h1 style={{
              fontFamily: "'Plus Jakarta Sans', sans-serif",
              fontSize: isMobile ? '40px' : isTablet ? '56px' : '80px',
              fontWeight: 500,
              color: '#fff',
              lineHeight: isMobile ? 1.2 : 1.1,
              letterSpacing: isMobile ? '-1px' : '-3px',
              marginBottom: isMobile ? '35px' : '24px',
              padding: isMobile ? '0 20px' : 0,
            }}>
              Beyond the <span style={{ fontStyle: 'italic' }}>original</span>
              <br />
              branding and{' '}
              <span
                ref={heroImageRef}
                style={{
                  display: 'inline-block',
                  width: isMobile ? '57px' : '125px',
                  height: isMobile ? '43px' : '67px',
                  backgroundColor: '#fff',
                  borderRadius: '300px',
                  verticalAlign: 'middle',
                  marginLeft: isMobile ? '4px' : '0',
                  marginRight: isMobile ? '0' : '16px',
                  overflow: 'hidden',
                  transition: 'opacity 0.2s ease',
                }}>
                {(isMobile ? (pageContent.heroImageMobile || pageContent.heroImage) : pageContent.heroImage) && (
                  <img
                    src={getImageUrl(isMobile ? (pageContent.heroImageMobile || pageContent.heroImage) : pageContent.heroImage)}
                    alt=""
                    style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                  />
                )}
              </span>
              <br />
              UI UX design agency
            </h1>

            {/* Description */}
            <p style={{
              fontFamily: "'Plus Jakarta Sans', sans-serif",
              fontSize: '16px',
              fontWeight: 500,
              color: '#fff',
              lineHeight: '28px',
              maxWidth: isMobile ? '350px' : '531px',
              marginBottom: isMobile ? '58px' : '40px',
              margin: isMobile ? '0 auto 58px' : '0 0 40px 0',
              textAlign: isMobile ? 'center' : 'left',
            }}>
              {pageContent.heroDescription || 'We are UX/UI agency helping ambitious companies and visionary entrepreneurs bring the next design revolution.'}
            </p>

            {/* Buttons */}
            <div style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: isMobile ? 'center' : 'flex-start',
              gap: '16px',
              marginBottom: '20px',
            }}>
              <Link to="/contact" style={{
                display: 'inline-flex',
                alignItems: 'center',
                justifyContent: 'center',
                padding: '12px 24px',
                height: isMobile ? '54px' : '64px',
                width: isMobile ? '347px' : 'auto',
                minWidth: isMobile ? 'auto' : '216px',
                backgroundColor: '#fff',
                color: '#000',
                borderRadius: '200px',
                textDecoration: 'none',
                fontFamily: "'Plus Jakarta Sans', sans-serif",
                fontSize: '20px',
                fontWeight: 600,
              }}>
                {pageContent.heroButton1Text || 'Schedule Call'}
              </Link>
              {!isMobile && (
                <Link to="/work" style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  padding: '12px 24px',
                  height: '64px',
                  minWidth: '200px',
                  backgroundColor: 'transparent',
                  color: '#fff',
                  border: '1px solid #fff',
                  borderRadius: '200px',
                  textDecoration: 'none',
                  fontFamily: "'Plus Jakarta Sans', sans-serif",
                  fontSize: '20px',
                  fontWeight: 600,
                }}>
                  {pageContent.heroButton2Text || 'Our Work'}
                </Link>
              )}
            </div>

            {/* Get instant response */}
            <div style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: isMobile ? 'center' : 'flex-start',
              gap: '12px',
            }}>
              <img src={vectorIcon} alt="" style={{ width: '18px', height: '20px', filter: 'brightness(0) invert(1)' }} />
              <span style={{
                fontFamily: "'Plus Jakarta Sans', sans-serif",
                fontSize: '16px',
                fontWeight: 500,
                color: '#fff',
              }}>
                {pageContent.heroInstantText || 'Get instant response'}
              </span>
            </div>
          </div>

          {/* Decorative 3D Elements - Right Side (Desktop only) */}
          {!isMobile && (
            <>
              {/* Position 1 - Top right 3D element */}
              <img
                src={heroDecor1}
                alt=""
                style={{
                  position: 'absolute',
                  right: '110px',
                  top: '530px',
                  width: '220px',
                  height: 'auto',
                  zIndex: 2,
                }}
              />
              {/* Position 2 - Bottom center-right 3D element */}
              <img
                src={heroDecor2}
                alt=""
                style={{
                  position: 'absolute',
                  right: '510px',
                  bottom: '-100px',
                  width: '160px',
                  height: 'auto',
                  zIndex: 2,
                }}
              />
            </>
          )}
        </section>
      </EditableSection>
      )}

      {/* Target Section for Animated Image - Full width image display (works on both mobile and desktop) */}
      <section
        ref={targetSectionRef}
        style={{
          width: '100%',
          height: isMobile ? '792px' : '832px',
          position: 'relative',
          overflow: 'hidden',
        }}
      >
        {/* Static image that appears when animation completes */}
        {(pageContent.heroImage || pageContent.heroImageMobile) && (
          <img
            src={getImageUrl(isMobile ? (pageContent.heroImageMobile || pageContent.heroImage) : pageContent.heroImage)}
            alt=""
            style={{
              width: '100%',
              height: '100%',
              objectFit: 'cover',
              opacity: 0,
            }}
          />
        )}
      </section>

      {/* Partner Brands Section */}
      {shouldRenderSection('partners') && (
      <EditableSection sectionId="partners" label="Partner Brands" isEditorMode={isEditorMode} isSelected={selectedSection === 'partners'} isHidden={isSectionHidden('partners')}>
        <section style={{
          padding: isMobile ? '64px 20px' : isTablet ? '60px 40px' : '80px 100px',
          textAlign: 'center',
        }}>
          <p style={{
            fontFamily: "'Plus Jakarta Sans', sans-serif",
            fontSize: isMobile ? '20px' : '28px',
            fontWeight: isMobile ? 600 : 400,
            fontStyle: 'normal',
            color: '#000',
            lineHeight: isMobile ? '30px' : 'normal',
            width: isMobile ? '390px' : '645px',
            maxWidth: '100%',
            margin: `0 auto ${isMobile ? '36px' : '40px'}`,
            textAlign: 'center',
          }}>
            {pageContent.partnerTitle}
          </p>

          {/* Logo Grid - Two rows like About page */}
          {(() => {
            // Helper to get logo path
            const getLogoPath = (logo) => {
              if (typeof logo === 'string') return logo;
              if (typeof logo === 'object' && logo !== null) {
                return logo.image || logo.url || logo.path || logo.src || '';
              }
              return '';
            };

            // Split logos into two rows (6 in first row, rest in second)
            const logosRow1 = partnerLogos.slice(0, 6);
            const logosRow2 = isMobile ? [] : partnerLogos.slice(6, 10);

            // Render logo item
            const renderLogo = (logo, index) => {
              const logoPath = getLogoPath(logo);
              if (!logoPath) {
                if (logo?.name) {
                  return (
                    <span key={index} style={{
                      fontFamily: "'Plus Jakarta Sans', 'Inter', sans-serif",
                      fontSize: isMobile ? '14px' : isTablet ? '16px' : '18px',
                      color: '#999',
                      fontWeight: 500,
                      height: isMobile ? '28px' : isTablet ? '40px' : '48px',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                    }}>
                      {logo.name}
                    </span>
                  );
                }
                return null;
              }
              return (
                <img
                  key={index}
                  src={getImageUrl(logoPath)}
                  alt={logo?.name || `Partner logo ${index + 1}`}
                  style={{
                    width: 'auto',
                    height: isMobile ? '28px' : isTablet ? '40px' : '48px',
                    objectFit: 'contain',
                    filter: 'grayscale(100%)',
                    opacity: 0.6,
                    transition: 'opacity 0.3s, filter 0.3s',
                  }}
                  onMouseEnter={(e) => {
                    e.target.style.opacity = '1';
                    e.target.style.filter = 'grayscale(0%)';
                  }}
                  onMouseLeave={(e) => {
                    e.target.style.opacity = '0.6';
                    e.target.style.filter = 'grayscale(100%)';
                  }}
                  onError={(e) => {
                    e.target.style.display = 'none';
                  }}
                />
              );
            };

            if (partnerLogos.length === 0) {
              // Fallback text logos
              return (
                <div style={{
                  display: 'flex',
                  flexWrap: 'wrap',
                  justifyContent: 'center',
                  alignItems: 'center',
                  gap: isMobile ? '24px 32px' : isTablet ? '40px' : '81px',
                  maxWidth: '1200px',
                  margin: '0 auto',
                }}>
                  {fallbackLogos.map((logo, index) => (
                    <span key={index} style={{
                      fontFamily: "'Plus Jakarta Sans', 'Inter', sans-serif",
                      fontSize: isMobile ? '14px' : isTablet ? '16px' : '18px',
                      color: '#999',
                      fontWeight: 500,
                    }}>
                      {logo}
                    </span>
                  ))}
                </div>
              );
            }

            return (
              <>
                {/* Mobile: All logos in flex wrap */}
                {isMobile && (
                  <div style={{
                    display: 'flex',
                    flexWrap: 'wrap',
                    gap: '24px 32px',
                    justifyContent: 'center',
                  }}>
                    {partnerLogos.map((logo, index) => renderLogo(logo, index))}
                  </div>
                )}

                {/* Desktop/Tablet: Row 1 */}
                {!isMobile && (
                  <div style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: isTablet ? '40px' : '81px',
                    marginBottom: '56px',
                    flexWrap: 'nowrap',
                  }}>
                    {logosRow1.map((logo, index) => renderLogo(logo, index))}
                  </div>
                )}

                {/* Desktop/Tablet: Row 2 */}
                {!isMobile && logosRow2.length > 0 && (
                  <div style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: isTablet ? '40px' : '81px',
                    flexWrap: 'nowrap',
                  }}>
                    {logosRow2.map((logo, index) => renderLogo(logo, index + 6))}
                  </div>
                )}
              </>
            );
          })()}
        </section>
      </EditableSection>
      )}

      {/* Experience Section */}
      {shouldRenderSection('experience') && (
      <EditableSection sectionId="experience" label="Experience Section" isEditorMode={isEditorMode} isSelected={selectedSection === 'experience'} isHidden={isSectionHidden('experience')}>
        <section style={{
          backgroundColor: isMobile ? '#E1FFA0' : 'transparent',
          borderRadius: isMobile ? '0 0 300px 300px' : '0',
          padding: isMobile ? '48px 20px 80px' : isTablet ? '60px 40px' : '80px 100px',
          textAlign: 'center',
          minHeight: isMobile ? '733px' : 'auto',
          marginTop: isMobile ? '-100px' : '0',
          position: 'relative',
          zIndex: 1,
        }}>
          <div style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: isMobile ? '11px' : '0',
            marginBottom: isMobile ? '40px' : '16px',
          }}>
            <h2 style={{
              fontFamily: "'Plus Jakarta Sans', sans-serif",
              fontSize: isMobile ? '28px' : isTablet ? '36px' : '48px',
              fontWeight: 500,
              color: '#000',
              lineHeight: isMobile ? 'normal' : 1.2,
              letterSpacing: isMobile ? '-0.5px' : '0',
              margin: 0,
              width: isMobile ? '373px' : 'auto',
              maxWidth: '100%',
            }}>
              <span style={{ fontStyle: 'italic', fontWeight: 600 }}>{pageContent.experienceTitle1}</span>{' '}
              {pageContent.experienceTitle2}
            </h2>
            <h2 style={{
              fontFamily: "'Plus Jakarta Sans', sans-serif",
              fontSize: isMobile ? '28px' : isTablet ? '36px' : '48px',
              fontWeight: 500,
              color: '#000',
              lineHeight: isMobile ? 'normal' : 1.2,
              letterSpacing: isMobile ? '-0.5px' : '0',
              margin: 0,
              width: isMobile ? '373px' : 'auto',
              maxWidth: '100%',
              display: isMobile ? 'block' : 'none',
            }}>
              <span style={{ fontStyle: 'italic', fontWeight: 600 }}>{pageContent.experienceTitle3}</span>{' '}
              {pageContent.experienceTitle4}
            </h2>
            {!isMobile && (
              <h2 style={{
                fontFamily: "'Plus Jakarta Sans', sans-serif",
                fontSize: isTablet ? '36px' : '48px',
                fontWeight: 500,
                color: '#000',
                lineHeight: 1.2,
                margin: 0,
              }}>
                <span style={{ fontStyle: 'italic', fontWeight: 600 }}>{pageContent.experienceTitle3}</span>{' '}
                {pageContent.experienceTitle4}
              </h2>
            )}
          </div>
          {!isMobile && (
            <p style={{
              fontFamily: "'Plus Jakarta Sans', sans-serif",
              fontSize: '16px',
              fontWeight: 400,
              color: '#666',
              maxWidth: '600px',
              margin: '0 auto',
            }}>
              {pageContent.experienceDescription}
            </p>
          )}
        </section>
      </EditableSection>
      )}

      {/* Projects Showcase Section */}
      {shouldRenderSection('projects') && (
      <EditableSection sectionId="projects" label="Projects Section" isEditorMode={isEditorMode} isSelected={selectedSection === 'projects'} isHidden={isSectionHidden('projects')}>
        <section style={{
          padding: isMobile ? '0 0 40px 0' : '0 0 60px 0',
        }}>
          {/* Project Cards */}
          <div style={{
            display: 'flex',
            flexDirection: 'column',
            gap: isMobile ? '0' : '0',
          }}>
            {works.length > 0 ? works.map((work, index) => (
              <div key={work._id || index} style={{
                display: 'flex',
                flexDirection: isMobile ? 'column' : index % 2 === 0 ? 'row' : 'row-reverse',
                minHeight: isMobile ? 'auto' : '500px',
                backgroundColor: projectColors[index % projectColors.length],
                borderRadius: isMobile ? '0 0 300px 300px' : '0',
                overflow: 'hidden',
                marginTop: isMobile && index > 0 ? '-200px' : '0',
                position: 'relative',
                zIndex: isMobile ? 3 - index : 'auto',
              }}>
                {/* Image Section - First on mobile */}
                <div style={{
                  flex: 1,
                  backgroundColor: projectColors[index % projectColors.length],
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  padding: isMobile ? '60px 25px 40px' : '40px',
                  position: 'relative',
                  order: isMobile ? 1 : 2,
                }}>
                  {work.featuredImage ? (
                    <img
                      src={getImageUrl(work.featuredImage)}
                      alt={work.title}
                      style={{
                        maxWidth: '100%',
                        maxHeight: isMobile ? '365px' : '400px',
                        width: isMobile ? '379px' : 'auto',
                        objectFit: 'cover',
                        borderRadius: '8px',
                      }}
                    />
                  ) : (
                    <div style={{
                      width: isMobile ? '379px' : '100%',
                      height: isMobile ? '365px' : '300px',
                      backgroundColor: 'rgba(255,255,255,0.2)',
                      borderRadius: '8px',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      color: projectColors[index % projectColors.length] === '#2558BF' ? '#fff' : '#000',
                    }}>
                      Project Image
                    </div>
                  )}
                  {/* Arrow Button */}
                  {!isMobile && index % 2 !== 0 && (
                    <Link to={`/work/${work.slug || work._id}`} style={{
                      position: 'absolute',
                      left: '-28px',
                      top: '50%',
                      transform: 'translateY(-50%)',
                      width: '56px',
                      height: '56px',
                      borderRadius: '50%',
                      backgroundColor: '#fff',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
                      textDecoration: 'none',
                    }}>
                      <span style={{ fontSize: '24px', color: '#000' }}>→</span>
                    </Link>
                  )}
                </div>
                {/* Text Section - Below image on mobile */}
                <div style={{
                  flex: isMobile ? 'none' : 1,
                  backgroundColor: projectColors[index % projectColors.length],
                  padding: isMobile ? '20px 25px 100px' : '60px',
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'flex-start',
                  alignItems: isMobile ? 'center' : 'flex-start',
                  order: isMobile ? 2 : 1,
                }}>
                  <h3 style={{
                    fontFamily: "'Plus Jakarta Sans', sans-serif",
                    fontSize: isMobile ? '26px' : '32px',
                    fontWeight: 500,
                    color: projectColors[index % projectColors.length] === '#2558BF' ? '#fff' : '#000',
                    marginBottom: '8px',
                    textAlign: isMobile ? 'center' : 'left',
                    width: isMobile ? '315px' : 'auto',
                  }}>
                    <span style={{ fontStyle: 'italic', fontWeight: 600 }}>{work.title || 'Project Name'}</span>
                    <span style={{ fontWeight: 500 }}> , and the description goes here</span>
                  </h3>
                </div>
              </div>
            )) : (
              // Placeholder projects if no works
              [0, 1, 2].map((index) => (
                <div key={index} style={{
                  display: 'flex',
                  flexDirection: isMobile ? 'column' : index % 2 === 0 ? 'row' : 'row-reverse',
                  minHeight: isMobile ? 'auto' : '500px',
                  backgroundColor: projectColors[index],
                  borderRadius: isMobile ? '0 0 300px 300px' : '0',
                  overflow: 'hidden',
                  marginTop: isMobile && index > 0 ? '-200px' : '0',
                  position: 'relative',
                  zIndex: isMobile ? 3 - index : 'auto',
                }}>
                  {/* Image Section - First on mobile */}
                  <div style={{
                    flex: 1,
                    backgroundColor: projectColors[index],
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    padding: isMobile ? '60px 25px 40px' : '40px',
                    order: isMobile ? 1 : 2,
                  }}>
                    <div style={{
                      width: isMobile ? '379px' : '100%',
                      height: isMobile ? '365px' : '300px',
                      backgroundColor: 'rgba(255,255,255,0.2)',
                      borderRadius: '8px',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      color: projectColors[index] === '#2558BF' ? '#fff' : '#000',
                    }}>
                      Project Image
                    </div>
                  </div>
                  {/* Text Section - Below image on mobile */}
                  <div style={{
                    flex: isMobile ? 'none' : 1,
                    backgroundColor: projectColors[index],
                    padding: isMobile ? '20px 25px 100px' : '60px',
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'flex-start',
                    alignItems: isMobile ? 'center' : 'flex-start',
                    order: isMobile ? 2 : 1,
                  }}>
                    <h3 style={{
                      fontFamily: "'Plus Jakarta Sans', sans-serif",
                      fontSize: isMobile ? '26px' : '32px',
                      fontWeight: 500,
                      color: projectColors[index] === '#2558BF' ? '#fff' : '#000',
                      textAlign: isMobile ? 'center' : 'left',
                      width: isMobile ? '315px' : 'auto',
                    }}>
                      <span style={{ fontStyle: 'italic', fontWeight: 600 }}>Project Name</span>
                      <span style={{ fontWeight: 500 }}> , and the description goes here</span>
                    </h3>
                  </div>
                </div>
              ))
            )}
          </div>
        </section>
      </EditableSection>
      )}

      {/* Want To See More Section */}
      {shouldRenderSection('wantMore') && (
      <EditableSection sectionId="wantMore" label="Want To See More" isEditorMode={isEditorMode} isSelected={selectedSection === 'wantMore'} isHidden={isSectionHidden('wantMore')}>
        <section style={{
          padding: isMobile ? '40px 20px' : '60px 100px',
          textAlign: 'center',
        }}>
          <h3 style={{
            fontFamily: "'Plus Jakarta Sans', sans-serif",
            fontSize: isMobile ? '20px' : '24px',
            fontWeight: 500,
            color: '#000',
            marginBottom: '16px',
          }}>
            {pageContent.wantMoreTitle}
          </h3>
          <Link to="/case-studies" style={{
            display: 'inline-flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: '12px 32px',
            backgroundColor: '#2558BF',
            color: '#fff',
            borderRadius: '100px',
            textDecoration: 'none',
            fontFamily: "'Plus Jakarta Sans', sans-serif",
            fontSize: '14px',
            fontWeight: 500,
          }}>
            {pageContent.wantMoreButtonText}
          </Link>
        </section>
      </EditableSection>
      )}

      {/* Real Numbers Section */}
      {shouldRenderSection('realNumbers') && (
      <EditableSection sectionId="realNumbers" label="Real Numbers Section" isEditorMode={isEditorMode} isSelected={selectedSection === 'realNumbers'} isHidden={isSectionHidden('realNumbers')}>
        <section style={{
          padding: isMobile ? '64px 22px' : isTablet ? '60px 40px' : '80px 100px',
          textAlign: 'center',
        }}>
          <h2 style={{
            fontFamily: "'Plus Jakarta Sans', sans-serif",
            fontSize: isMobile ? '28px' : isTablet ? '36px' : '42px',
            fontWeight: 500,
            color: '#000',
            marginBottom: isMobile ? '74px' : '48px',
            letterSpacing: isMobile ? '-0.5px' : '0',
          }}>
            <span style={{ fontStyle: 'italic', fontWeight: 500 }}>{pageContent.realNumbersTitle}</span>{' '}
            {pageContent.realNumbersTitleNormal}
          </h2>

          {/* Stats Grid */}
          <div style={{
            display: 'grid',
            gridTemplateColumns: isMobile ? 'repeat(2, 1fr)' : 'repeat(4, 1fr)',
            gap: isMobile ? '12px' : '24px',
            maxWidth: isMobile ? '386px' : '1000px',
            margin: '0 auto',
            marginBottom: isMobile ? '12px' : '32px',
          }}>
            {/* Stat 1 */}
            <div style={{
              padding: isMobile ? '24px 17px' : '32px',
              border: isMobile ? '1.5px solid rgba(0,0,0,0.05)' : '1px solid #E5E5E5',
              borderRadius: isMobile ? '16px' : '8px',
            }}>
              <div style={{
                fontFamily: "'Plus Jakarta Sans', sans-serif",
                fontSize: isMobile ? '32px' : '36px',
                fontWeight: 500,
                color: '#000',
                marginBottom: '10px',
                letterSpacing: isMobile ? '0.37px' : '0',
              }}>
                {pageContent.stat1Value}
              </div>
              <div style={{
                fontFamily: "'Plus Jakarta Sans', sans-serif",
                fontSize: '12px',
                fontWeight: 500,
                color: '#1f1f1f',
                letterSpacing: isMobile ? '-0.15px' : '0',
              }}>
                {pageContent.stat1Label}
              </div>
            </div>
            {/* Stat 2 */}
            <div style={{
              padding: isMobile ? '24px 17px' : '32px',
              border: isMobile ? '1.5px solid rgba(0,0,0,0.05)' : '1px solid #E5E5E5',
              borderRadius: isMobile ? '16px' : '8px',
            }}>
              <div style={{
                fontFamily: "'Plus Jakarta Sans', sans-serif",
                fontSize: isMobile ? '32px' : '36px',
                fontWeight: 500,
                color: '#000',
                marginBottom: '10px',
                letterSpacing: isMobile ? '0.37px' : '0',
              }}>
                {pageContent.stat2Value}
              </div>
              <div style={{
                fontFamily: "'Plus Jakarta Sans', sans-serif",
                fontSize: '12px',
                fontWeight: 500,
                color: '#1f1f1f',
                letterSpacing: isMobile ? '-0.15px' : '0',
              }}>
                {pageContent.stat2Label}
              </div>
            </div>
            {/* Stat 3 */}
            <div style={{
              padding: isMobile ? '24px 17px' : '32px',
              border: isMobile ? '1.5px solid rgba(0,0,0,0.05)' : '1px solid #E5E5E5',
              borderRadius: isMobile ? '16px' : '8px',
            }}>
              <div style={{
                fontFamily: "'Plus Jakarta Sans', sans-serif",
                fontSize: isMobile ? '32px' : '36px',
                fontWeight: 500,
                color: '#000',
                marginBottom: '10px',
                letterSpacing: isMobile ? '0.37px' : '0',
              }}>
                {pageContent.stat3Value}
              </div>
              <div style={{
                fontFamily: "'Plus Jakarta Sans', sans-serif",
                fontSize: '12px',
                fontWeight: 500,
                color: '#1f1f1f',
                letterSpacing: isMobile ? '-0.15px' : '0',
              }}>
                {pageContent.stat3Label}
              </div>
            </div>
            {/* Stat 4 */}
            <div style={{
              padding: isMobile ? '24px 17px' : '32px',
              border: isMobile ? '1.5px solid rgba(0,0,0,0.05)' : '1px solid #E5E5E5',
              borderRadius: isMobile ? '16px' : '8px',
            }}>
              <div style={{
                fontFamily: "'Plus Jakarta Sans', sans-serif",
                fontSize: isMobile ? '32px' : '36px',
                fontWeight: 500,
                color: '#000',
                marginBottom: '10px',
                letterSpacing: isMobile ? '0.37px' : '0',
              }}>
                {pageContent.stat4Value}
              </div>
              <div style={{
                fontFamily: "'Plus Jakarta Sans', sans-serif",
                fontSize: '12px',
                fontWeight: 500,
                color: '#1f1f1f',
                letterSpacing: isMobile ? '-0.15px' : '0',
                color: '#666',
              }}>
                {pageContent.stat4Label}
              </div>
            </div>
          </div>

          {/* Stat 5 with Image */}
          <div style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            gap: '16px',
          }}>
            {pageContent.stat5Image ? (
              <img src={getImageUrl(pageContent.stat5Image)} alt="" style={{ width: '80px', height: '80px', borderRadius: '8px', objectFit: 'cover' }} />
            ) : (
              <div style={{ width: '80px', height: '80px', backgroundColor: '#E5E5E5', borderRadius: '8px' }} />
            )}
            <div style={{ textAlign: 'left' }}>
              <div style={{
                fontFamily: "'Plus Jakarta Sans', sans-serif",
                fontSize: isMobile ? '24px' : '36px',
                fontWeight: 600,
                color: '#000',
              }}>
                {pageContent.stat5Value}
              </div>
              <div style={{
                fontFamily: "'Plus Jakarta Sans', sans-serif",
                fontSize: isMobile ? '12px' : '14px',
                fontWeight: 400,
                color: '#666',
              }}>
                {pageContent.stat5Label}
              </div>
            </div>
          </div>
        </section>
      </EditableSection>
      )}

      {/* Services Section */}
      {shouldRenderSection('services') && (
      <EditableSection sectionId="services" label="Services Section" isEditorMode={isEditorMode} isSelected={selectedSection === 'services'} isHidden={isSectionHidden('services')}>
        <section style={{
          padding: isMobile ? '40px 20px' : isTablet ? '60px 40px' : '80px 100px',
        }}>
          {/* Title and CTA Row */}
          <div style={{
            display: 'flex',
            flexDirection: isMobile ? 'column' : 'row',
            justifyContent: 'space-between',
            alignItems: isMobile ? 'flex-start' : 'flex-end',
            marginBottom: isMobile ? '32px' : '48px',
            gap: isMobile ? '24px' : '40px',
          }}>
            <h2 style={{
              fontFamily: "'Plus Jakarta Sans', sans-serif",
              fontSize: isMobile ? '28px' : isTablet ? '36px' : '42px',
              fontWeight: 400,
              color: '#000',
              maxWidth: '500px',
              lineHeight: 1.2,
            }}>
              <span style={{ fontStyle: 'italic' }}>{pageContent.servicesTitle}</span>{' '}
              {pageContent.servicesTitleNormal}
            </h2>
            <div style={{ textAlign: isMobile ? 'left' : 'right' }}>
              <Link to="/contact" style={{
                display: 'inline-flex',
                alignItems: 'center',
                justifyContent: 'center',
                padding: '16px 32px',
                backgroundColor: '#2558BF',
                color: '#fff',
                borderRadius: '100px',
                textDecoration: 'none',
                fontFamily: "'Plus Jakarta Sans', sans-serif",
                fontSize: '16px',
                fontWeight: 500,
                marginBottom: '12px',
              }}>
                {pageContent.ctaMidButtonText}
              </Link>
              <div style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: isMobile ? 'flex-start' : 'flex-end',
                gap: '8px',
              }}>
                <img src={vectorIcon} alt="" style={{ width: '14px', height: '14px' }} />
                <span style={{
                  fontFamily: "'Plus Jakarta Sans', sans-serif",
                  fontSize: '14px',
                  color: '#666',
                }}>
                  {pageContent.ctaMidInstantText}
                </span>
              </div>
            </div>
          </div>

          {/* Services Cards Carousel */}
          <div style={{
            display: 'flex',
            gap: '16px',
            overflowX: isMobile ? 'auto' : 'visible',
            paddingBottom: isMobile ? '16px' : '0',
          }}>
            {services.map((service, index) => (
              <div key={index} style={{
                flex: isMobile ? '0 0 280px' : 1,
                backgroundColor: '#1A1A1A',
                borderRadius: '16px',
                padding: '24px',
                minHeight: '300px',
                display: 'flex',
                flexDirection: 'column',
              }}>
                <h4 style={{
                  fontFamily: "'Plus Jakarta Sans', sans-serif",
                  fontSize: '20px',
                  fontWeight: 600,
                  color: '#fff',
                  marginBottom: '16px',
                }}>
                  {service.title}
                </h4>
                <p style={{
                  fontFamily: "'Plus Jakarta Sans', sans-serif",
                  fontSize: '14px',
                  fontWeight: 400,
                  color: '#999',
                  lineHeight: 1.6,
                  marginBottom: '24px',
                }}>
                  {service.description}
                </p>
                <div style={{
                  marginTop: 'auto',
                  height: '120px',
                  backgroundColor: '#2A2A2A',
                  borderRadius: '8px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  overflow: 'hidden',
                }}>
                  {service.image ? (
                    <img src={getImageUrl(service.image)} alt={service.title} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                  ) : (
                    <div style={{
                      width: '60px',
                      height: '60px',
                      backgroundColor: '#3A3A3A',
                      borderRadius: '8px',
                    }} />
                  )}
                </div>
              </div>
            ))}
          </div>

          {/* Carousel Navigation */}
          <div style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            gap: '16px',
            marginTop: '24px',
          }}>
            <button
              onClick={() => setCurrentServiceIndex(prev => Math.max(0, prev - 1))}
              style={{
                width: '40px',
                height: '40px',
                borderRadius: '50%',
                border: '1px solid #E5E5E5',
                backgroundColor: '#fff',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              ←
            </button>
            <span style={{
              fontFamily: "'Plus Jakarta Sans', sans-serif",
              fontSize: '14px',
              color: '#666',
            }}>
              {currentServiceIndex + 1} / {services.length > 0 ? Math.ceil(services.length) : 12}
            </span>
            <button
              onClick={() => setCurrentServiceIndex(prev => prev + 1)}
              style={{
                width: '40px',
                height: '40px',
                borderRadius: '50%',
                border: '1px solid #E5E5E5',
                backgroundColor: '#fff',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              →
            </button>
          </div>
        </section>
      </EditableSection>
      )}

      {/* Testimonial Section - Connected to About Page */}
      <section style={{
        padding: isMobile ? '40px 20px' : isTablet ? '60px 40px' : '80px 100px',
        textAlign: 'center',
      }}>
        <h3 style={{
          fontFamily: "'Plus Jakarta Sans', sans-serif",
          fontSize: isMobile ? '24px' : isTablet ? '32px' : '36px',
          fontWeight: 400,
          color: '#000',
          marginBottom: isMobile ? '32px' : '48px',
        }}>
          <span style={{ fontStyle: 'italic' }}>{testimonialData.clientLabelItalic}</span>{' '}
          {testimonialData.clientLabelNormal}
        </h3>

        {/* Testimonial Content */}
        <div style={{
          display: 'flex',
          flexDirection: isMobile ? 'column' : 'row',
          alignItems: isMobile ? 'flex-start' : 'center',
          justifyContent: 'center',
          gap: isMobile ? '24px' : '60px',
          maxWidth: '900px',
          margin: '0 auto',
        }}>
          {/* Quote */}
          <div style={{ flex: 1, textAlign: 'left' }}>
            <div style={{ fontSize: '48px', color: '#000', lineHeight: 1, marginBottom: '16px' }}>"</div>
            <p style={{
              fontFamily: "'Plus Jakarta Sans', sans-serif",
              fontSize: isMobile ? '16px' : '18px',
              fontWeight: 400,
              color: '#000',
              lineHeight: 1.6,
              marginBottom: '8px',
            }}>
              {testimonialData.testimonialQuote1}
            </p>
            <p style={{
              fontFamily: "'Plus Jakarta Sans', sans-serif",
              fontSize: isMobile ? '16px' : '18px',
              fontWeight: 400,
              color: '#000',
              lineHeight: 1.6,
              marginBottom: '24px',
            }}>
              {testimonialData.testimonialQuote2}
            </p>

            {/* Stats */}
            <div style={{
              display: 'flex',
              gap: '24px',
              borderTop: '1px solid #E5E5E5',
              paddingTop: '16px',
            }}>
              {testimonialData.testimonialStats.map((stat, index) => (
                <div key={index} style={{
                  borderRight: index < testimonialData.testimonialStats.length - 1 ? '1px solid #E5E5E5' : 'none',
                  paddingRight: index < testimonialData.testimonialStats.length - 1 ? '24px' : '0',
                }}>
                  <div style={{
                    fontFamily: "'Plus Jakarta Sans', sans-serif",
                    fontSize: isMobile ? '20px' : '24px',
                    fontWeight: 600,
                    color: '#000',
                  }}>
                    {stat.value}
                  </div>
                  <div style={{
                    fontFamily: "'Plus Jakarta Sans', sans-serif",
                    fontSize: '12px',
                    fontWeight: 400,
                    color: '#666',
                  }}>
                    {stat.label}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Author */}
          <div style={{ textAlign: 'center' }}>
            {testimonialData.testimonialImage ? (
              <img
                src={getImageUrl(testimonialData.testimonialImage)}
                alt={testimonialData.testimonialAuthor}
                style={{
                  width: isMobile ? '100px' : '150px',
                  height: isMobile ? '100px' : '150px',
                  borderRadius: '50%',
                  objectFit: 'cover',
                  marginBottom: '16px',
                }}
              />
            ) : (
              <div style={{
                width: isMobile ? '100px' : '150px',
                height: isMobile ? '100px' : '150px',
                borderRadius: '50%',
                backgroundColor: '#E5E5E5',
                marginBottom: '16px',
                margin: '0 auto 16px',
              }} />
            )}
            <p style={{
              fontFamily: "'Plus Jakarta Sans', sans-serif",
              fontSize: '16px',
              fontWeight: 600,
              color: '#000',
              marginBottom: '4px',
            }}>
              {testimonialData.testimonialAuthor}
            </p>
            <p style={{
              fontFamily: "'Plus Jakarta Sans', sans-serif",
              fontSize: '14px',
              fontWeight: 400,
              color: '#666',
              fontStyle: 'italic',
            }}>
              {testimonialData.testimonialRole}
            </p>
          </div>
        </div>

        {/* Navigation */}
        <div style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          gap: '16px',
          marginTop: '32px',
        }}>
          <button style={{
            width: '40px',
            height: '40px',
            borderRadius: '50%',
            border: '1px solid #E5E5E5',
            backgroundColor: '#fff',
            cursor: 'pointer',
          }}>
            ←
          </button>
          <button style={{
            width: '40px',
            height: '40px',
            borderRadius: '50%',
            border: '1px solid #E5E5E5',
            backgroundColor: '#fff',
            cursor: 'pointer',
          }}>
            →
          </button>
        </div>
      </section>

      {/* Brands Section */}
      {shouldRenderSection('brands') && (
      <EditableSection sectionId="brands" label="Brands Section" isEditorMode={isEditorMode} isSelected={selectedSection === 'brands'} isHidden={isSectionHidden('brands')}>
        <section style={{
          padding: isMobile ? '40px 20px' : isTablet ? '60px 40px' : '80px 100px',
        }}>
          <h2 style={{
            fontFamily: "'Plus Jakarta Sans', sans-serif",
            fontSize: isMobile ? '28px' : isTablet ? '36px' : '42px',
            fontWeight: 400,
            color: '#000',
            marginBottom: '16px',
          }}>
            {pageContent.brandsTitle}{' '}
            <span style={{ fontStyle: 'italic' }}>{pageContent.brandsTitleItalic}</span>
            <br />
            <span style={{ fontStyle: 'italic' }}>{pageContent.brandsTitleEnd}</span>
          </h2>
          <p style={{
            fontFamily: "'Plus Jakarta Sans', sans-serif",
            fontSize: isMobile ? '14px' : '16px',
            fontWeight: 400,
            color: '#666',
            maxWidth: '500px',
            marginBottom: '32px',
          }}>
            {pageContent.brandsDescription}
          </p>

          {/* Accordion */}
          <div style={{ maxWidth: '800px' }}>
            {accordionItems.map((item, index) => (
              <div key={index} style={{
                borderTop: '1px solid #E5E5E5',
                borderBottom: index === accordionItems.length - 1 ? '1px solid #E5E5E5' : 'none',
              }}>
                <button
                  onClick={() => setExpandedAccordion(expandedAccordion === index ? -1 : index)}
                  style={{
                    width: '100%',
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    padding: '20px 0',
                    backgroundColor: 'transparent',
                    border: 'none',
                    cursor: 'pointer',
                  }}
                >
                  <span style={{
                    fontFamily: "'Plus Jakarta Sans', sans-serif",
                    fontSize: isMobile ? '16px' : '20px',
                    fontWeight: 500,
                    color: '#000',
                  }}>
                    {item.title}
                  </span>
                  <span style={{
                    fontSize: '24px',
                    color: '#E2775A',
                    transform: expandedAccordion === index ? 'rotate(180deg)' : 'rotate(0deg)',
                    transition: 'transform 0.3s ease',
                  }}>
                    {expandedAccordion === index ? '←' : '→'}
                  </span>
                </button>
                {expandedAccordion === index && item.items.length > 0 && (
                  <div style={{
                    padding: '0 0 20px 0',
                    display: 'flex',
                    flexWrap: 'wrap',
                    gap: '8px 24px',
                  }}>
                    {item.items.map((subItem, subIndex) => (
                      <div key={subIndex} style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: '8px',
                      }}>
                        <span style={{
                          width: '6px',
                          height: '6px',
                          borderRadius: '50%',
                          backgroundColor: '#E2775A',
                        }} />
                        <span style={{
                          fontFamily: "'Plus Jakarta Sans', sans-serif",
                          fontSize: '14px',
                          color: '#666',
                        }}>
                          {subItem}
                        </span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* CTA Button */}
          <div style={{ marginTop: '40px', textAlign: isMobile ? 'center' : 'left' }}>
            <Link to="/contact" style={{
              display: 'inline-flex',
              alignItems: 'center',
              justifyContent: 'center',
              padding: '16px 32px',
              backgroundColor: '#2558BF',
              color: '#fff',
              borderRadius: '100px',
              textDecoration: 'none',
              fontFamily: "'Plus Jakarta Sans', sans-serif",
              fontSize: '16px',
              fontWeight: 500,
              marginBottom: '12px',
            }}>
              {pageContent.ctaMidButtonText}
            </Link>
            <div style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: isMobile ? 'center' : 'flex-start',
              gap: '8px',
              marginTop: '12px',
            }}>
              <img src={vectorIcon} alt="" style={{ width: '14px', height: '14px' }} />
              <span style={{
                fontFamily: "'Plus Jakarta Sans', sans-serif",
                fontSize: '14px',
                color: '#666',
              }}>
                {pageContent.ctaMidInstantText}
              </span>
            </div>
          </div>
        </section>
      </EditableSection>
      )}

      {/* CTA Section - Same as Work page */}
      {shouldRenderSection('cta') && (
      <EditableSection sectionId="cta" label="CTA Section" isEditorMode={isEditorMode} isSelected={selectedSection === 'cta'} isHidden={isSectionHidden('cta')}>
        <section style={{ backgroundColor: '#fff', padding: isMobile ? '0' : '60px 100px', marginBottom: isMobile ? '-150px' : '0' }}>
          <div style={{
            maxWidth: isMobile ? '100%' : '1240px',
            minHeight: isMobile ? '438px' : '500px',
            margin: '0 auto',
            borderTopLeftRadius: isMobile ? '160px' : '300px',
            borderTopRightRadius: isMobile ? '160px' : '300px',
            borderBottomLeftRadius: isMobile ? '0' : '300px',
            borderBottomRightRadius: isMobile ? '0' : '300px',
            backgroundColor: '#E2775A',
            position: 'relative',
            overflow: isMobile ? 'visible' : 'hidden',
            display: 'flex',
            flexDirection: isMobile ? 'column' : 'row',
            alignItems: 'center',
            padding: isMobile ? '60px 24px 80px 24px' : isTablet ? '48px 60px' : '60px 118px',
            paddingBottom: isMobile ? '214px' : undefined,
          }}>
            {/* Left Content */}
            <div style={{ maxWidth: isMobile ? '100%' : '600px', zIndex: 1, textAlign: isMobile ? 'center' : 'left', marginTop: isMobile ? '0' : '-50px' }}>
              <h2 style={{
                color: '#FFF',
                fontFamily: "'Plus Jakarta Sans', 'Inter', sans-serif",
                fontSize: isMobile ? '28px' : isTablet ? '36px' : '42px',
                fontWeight: 400,
                lineHeight: 'normal',
                letterSpacing: '-1px',
                marginBottom: isMobile ? '16px' : '10px',
              }}>
                {pageContent.ctaHeading}
              </h2>
              <p style={{
                color: '#FFF',
                fontFamily: "'Plus Jakarta Sans', 'Inter', sans-serif",
                fontSize: isMobile ? '16px' : '20px',
                fontWeight: 400,
                lineHeight: '28px',
                marginBottom: '8px',
              }}>
                {pageContent.ctaDescription1}
              </p>
              <p style={{
                color: '#FFF',
                fontFamily: "'Plus Jakarta Sans', 'Inter', sans-serif",
                fontSize: isMobile ? '16px' : '20px',
                fontWeight: 400,
                lineHeight: '28px',
                marginBottom: isMobile ? '16px' : '24px',
              }}>
                {pageContent.ctaDescription2}
              </p>
              <p style={{
                color: '#FFF',
                fontFamily: "'Plus Jakarta Sans', 'Inter', sans-serif",
                fontSize: isMobile ? '16px' : '20px',
                fontWeight: 400,
                lineHeight: '28px',
                marginBottom: isMobile ? '24px' : '32px',
              }}>
                {pageContent.ctaDescription3}
              </p>

              <Link to="/contact" style={{
                display: 'flex',
                width: isMobile ? '100%' : '346px',
                height: '64px',
                padding: '12px 24px',
                justifyContent: 'center',
                alignItems: 'center',
                gap: '12px',
                borderRadius: '200px',
                backgroundColor: '#FFF',
                textDecoration: 'none',
                marginBottom: '16px',
              }}>
                <span style={{
                  color: '#000',
                  fontFamily: "'Plus Jakarta Sans', 'Inter', sans-serif",
                  fontSize: isMobile ? '16px' : '20px',
                  fontWeight: 600,
                }}>
                  {pageContent.ctaButtonText}
                </span>
              </Link>

              <div style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: isMobile ? 'center' : 'flex-start',
                gap: '8px',
              }}>
                <img src={vectorIcon} alt="" style={{ width: '16px', height: '16px' }} />
                <span style={{
                  color: '#FFF',
                  fontFamily: "'Plus Jakarta Sans', 'Inter', sans-serif",
                  fontSize: isMobile ? '14px' : '16px',
                }}>
                  {pageContent.ctaInstantText}
                </span>
              </div>
            </div>

            {/* Decorative Squares */}
            {!isMobile && (
              <div style={{
                position: 'absolute',
                right: '60px',
                top: '50%',
                transform: 'translateY(-50%)',
                display: 'grid',
                gridTemplateColumns: 'repeat(3, 1fr)',
                gap: '12px',
              }}>
                {[1, 2, 3, 4, 5, 6].map((i) => (
                  <div key={i} style={{
                    width: '100px',
                    height: '70px',
                    backgroundColor: 'rgba(255,255,255,0.2)',
                    borderRadius: '4px',
                  }} />
                ))}
              </div>
            )}
          </div>
        </section>
      </EditableSection>
      )}

      {/* FAQ Section */}
      {shouldRenderSection('faq') && (
      <EditableSection sectionId="faq" label="FAQ Section" isEditorMode={isEditorMode} isSelected={selectedSection === 'faq'} isHidden={isSectionHidden('faq')}>
        <section style={{
          padding: isMobile ? '40px 20px' : isTablet ? '60px 40px' : '80px 100px',
          marginTop: isMobile ? '150px' : '0',
        }}>
          <h2 style={{
            fontFamily: "'Plus Jakarta Sans', sans-serif",
            fontSize: isMobile ? '28px' : isTablet ? '36px' : '42px',
            fontWeight: 400,
            color: '#000',
            textAlign: 'center',
            marginBottom: isMobile ? '32px' : '48px',
          }}>
            <span style={{ fontStyle: 'italic' }}>{pageContent.faqTitle}</span>{' '}
            {pageContent.faqTitleNormal}
          </h2>

          {/* FAQ Items */}
          <div style={{ maxWidth: '800px', margin: '0 auto' }}>
            {faqItems.map((item, index) => (
              <div key={index} style={{
                borderTop: '1px solid #E5E5E5',
                borderBottom: index === faqItems.length - 1 ? '1px solid #E5E5E5' : 'none',
              }}>
                <button
                  onClick={() => setExpandedFaq(expandedFaq === index ? null : index)}
                  style={{
                    width: '100%',
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    padding: '20px 0',
                    backgroundColor: 'transparent',
                    border: 'none',
                    cursor: 'pointer',
                  }}
                >
                  <span style={{
                    fontFamily: "'Plus Jakarta Sans', sans-serif",
                    fontSize: isMobile ? '14px' : '16px',
                    fontWeight: 400,
                    color: '#000',
                    textAlign: 'left',
                  }}>
                    {item.question}
                  </span>
                  <span style={{
                    fontSize: '20px',
                    color: '#000',
                    marginLeft: '16px',
                  }}>
                    {expandedFaq === index ? '−' : '+'}
                  </span>
                </button>
                {expandedFaq === index && (
                  <div style={{
                    padding: '0 0 20px 0',
                  }}>
                    <p style={{
                      fontFamily: "'Plus Jakarta Sans', sans-serif",
                      fontSize: '14px',
                      fontWeight: 400,
                      color: '#666',
                      lineHeight: 1.6,
                    }}>
                      {item.answer}
                    </p>
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* Contact Link */}
          <p style={{
            fontFamily: "'Plus Jakarta Sans', sans-serif",
            fontSize: '14px',
            fontWeight: 400,
            color: '#666',
            textAlign: 'center',
            marginTop: '32px',
          }}>
            {pageContent.faqContactText}{' '}
            <Link to="/contact" style={{
              color: '#000',
              textDecoration: 'underline',
              fontWeight: 500,
            }}>
              {pageContent.faqContactLink}
            </Link>
          </p>
        </section>
      </EditableSection>
      )}

    </div>
  );
};

export default Home;
