import { useState, useEffect } from 'react';
import { pagesAPI, uploadAPI } from '../services/api';

const HomePageEditor = ({ onClose, onSave }) => {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [activeSection, setActiveSection] = useState('hero');
  const [formData, setFormData] = useState({
    // Hero Section
    heroImage: '',
    heroImageMobile: '',
    heroDescription: 'We are UX/UI agency helping ambitious companies and visionary entrepreneurs bring the next design revolution.',
    heroButton1Text: 'Schedule Call',
    heroButton2Text: 'Our Work',
    heroInstantText: 'Get instant response',
    // Partner Brands Section
    partnerTitle: 'Our partner brands have built their tribe and strong presence in the market',
    // Experience Section
    experienceTitle1: "You've",
    experienceTitle2: 'already experienced it.',
    experienceTitle3: 'You',
    experienceTitle4: "just didn't notice.",
    experienceDescription: 'We are UX/UI agency helping ambitious companies and visionary entrepreneurs bring the next design revolution.',
    // Want To See More
    wantMoreTitle: 'Want To See More?',
    wantMoreButtonText: 'View All Case Studies',
    // Real Numbers Section
    realNumbersTitle: 'Real Numbers.',
    realNumbersTitleNormal: 'Real Impacts',
    stat1Value: '$280,366',
    stat1Label: 'Total Revenue Generated by our clients',
    stat2Value: '261+',
    stat2Label: 'Stores Launched and counting',
    stat3Value: '5.8%',
    stat3Label: 'Average Conversion Rate vs 2.5% industry avg',
    stat4Value: '4.8/5',
    stat4Label: 'Client Satisfaction from 200+ reviews',
    stat5Value: '1,247+',
    stat5Label: 'Design revisions survived',
    stat5Image: '',
    // Services Section
    servicesTitle: 'Turning',
    servicesTitleNormal: 'Brand, Product, and Tech Into One Experience',
    service1Title: 'Research & Strategy',
    service1Description: 'Data and Insights are backbone of building successful products. We ensure laying a perspective that balances business objectives and customer expectations.',
    service1Image: '',
    service2Title: 'Development',
    service2Description: 'Data and Insights are backbone of building successful products. We ensure laying a perspective that balances business objectives and customer expectations.',
    service2Image: '',
    service3Title: 'Designing',
    service3Description: 'Data and Insights are backbone of building successful products. We ensure laying a perspective that balances business objectives and customer expectations.',
    service3Image: '',
    // CTA Button (mid page)
    ctaMidButtonText: 'Schedule Call',
    ctaMidInstantText: 'Get instant response',
    // Brands Section
    brandsTitle: "Brands don't",
    brandsTitleItalic: 'grow',
    brandsTitleEnd: 'by accident.',
    brandsDescription: 'Most get lost in the noise. We combine strategy, design, and clarity to turn ideas into brands people choose — and remember.',
    accordion1Title: 'See What Others Miss',
    accordion1Items: 'UX audit,Data Analysis,Marketing and Research,Information Architecture',
    accordion2Title: 'Shape What Matters',
    accordion2Items: '',
    accordion3Title: 'Craft What Converts',
    accordion3Items: '',
    accordion4Title: 'Scale What Works',
    accordion4Items: '',
    // CTA Section (bottom)
    ctaHeading: 'Your search for agency ends here...',
    ctaDescription1: 'We combine strategy, design, and performance to create',
    ctaDescription2: 'experiences that convert.',
    ctaDescription3: "Let's build something that moves the needle.",
    ctaButtonText: 'Schedule Call',
    ctaInstantText: 'Get instant response',
    // FAQ Section
    faqTitle: 'Frequently',
    faqTitleNormal: 'asked question',
    faq1Question: 'Lorem ipsum dolor sit amet consectetur?',
    faq1Answer: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    faq2Question: 'Lorem ipsum dolor sit amet consectetur?',
    faq2Answer: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    faq3Question: 'Lorem ipsum dolor sit amet consectetur?',
    faq3Answer: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    faq4Question: 'Lorem ipsum dolor sit amet consectetur?',
    faq4Answer: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    faq5Question: 'Lorem ipsum dolor sit amet consectetur?',
    faq5Answer: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    faqContactText: "Any more questions, we'll be happy to answer.",
    faqContactLink: 'CONTACT US',
  });

  useEffect(() => {
    fetchPageData();
  }, []);

  const fetchPageData = async () => {
    try {
      const response = await pagesAPI.getOne('home');
      if (response.data.data && response.data.data.content) {
        setFormData((prev) => ({
          ...prev,
          ...response.data.data.content,
        }));
      }
    } catch (error) {
      console.log('Using default content for home page');
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleImageUpload = async (e, fieldName) => {
    const file = e.target.files[0];
    if (!file) return;

    const formDataUpload = new FormData();
    formDataUpload.append('image', file);

    try {
      const response = await uploadAPI.uploadImage(formDataUpload);
      setFormData((prev) => ({
        ...prev,
        [fieldName]: response.data.url,
      }));
    } catch (error) {
      console.error('Error uploading image:', error);
      alert('Error uploading image. Please try again.');
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setSaving(true);
    try {
      await pagesAPI.update('home', {
        name: 'home',
        title: 'Home Page',
        content: formData,
      });
      alert('Home page updated successfully!');
      if (onSave) onSave();
      if (onClose) onClose();
    } catch (error) {
      console.error('Error saving home page:', error);
      alert('Error saving page. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  const sections = [
    { id: 'hero', label: 'Hero' },
    { id: 'partners', label: 'Partners' },
    { id: 'experience', label: 'Experience' },
    { id: 'wantMore', label: 'Want More' },
    { id: 'realNumbers', label: 'Real Numbers' },
    { id: 'services', label: 'Services' },
    { id: 'brands', label: 'Brands' },
    { id: 'cta', label: 'CTA' },
    { id: 'faq', label: 'FAQ' },
  ];

  const inputStyle = {
    width: '100%',
    padding: '10px 12px',
    border: '1px solid #E5E5E5',
    borderRadius: '8px',
    fontSize: '14px',
    marginBottom: '16px',
  };

  const labelStyle = {
    display: 'block',
    fontSize: '14px',
    fontWeight: 500,
    color: '#333',
    marginBottom: '6px',
  };

  const sectionStyle = {
    backgroundColor: '#fff',
    borderRadius: '12px',
    padding: '24px',
    marginBottom: '24px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
  };

  const imagePreviewStyle = {
    width: '100%',
    maxWidth: '200px',
    height: '120px',
    objectFit: 'cover',
    borderRadius: '8px',
    marginBottom: '8px',
  };

  if (loading) {
    return (
      <div style={{ padding: '40px', textAlign: 'center' }}>
        <p>Loading...</p>
      </div>
    );
  }

  return (
    <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '24px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
        <h1 style={{ fontSize: '24px', fontWeight: 600 }}>Edit Home Page</h1>
        <div style={{ display: 'flex', gap: '12px' }}>
          <button
            onClick={onClose}
            style={{
              padding: '10px 20px',
              backgroundColor: '#fff',
              border: '1px solid #E5E5E5',
              borderRadius: '8px',
              cursor: 'pointer',
            }}
          >
            Cancel
          </button>
          <button
            onClick={handleSubmit}
            disabled={saving}
            style={{
              padding: '10px 20px',
              backgroundColor: '#2558BF',
              color: '#fff',
              border: 'none',
              borderRadius: '8px',
              cursor: 'pointer',
              opacity: saving ? 0.7 : 1,
            }}
          >
            {saving ? 'Saving...' : 'Save Changes'}
          </button>
        </div>
      </div>

      {/* Section Tabs */}
      <div style={{ display: 'flex', gap: '8px', marginBottom: '24px', flexWrap: 'wrap' }}>
        {sections.map((section) => (
          <button
            key={section.id}
            onClick={() => setActiveSection(section.id)}
            style={{
              padding: '8px 16px',
              backgroundColor: activeSection === section.id ? '#2558BF' : '#fff',
              color: activeSection === section.id ? '#fff' : '#333',
              border: '1px solid #E5E5E5',
              borderRadius: '20px',
              cursor: 'pointer',
              fontSize: '14px',
            }}
          >
            {section.label}
          </button>
        ))}
      </div>

      <form onSubmit={handleSubmit}>
        {/* Hero Section */}
        {activeSection === 'hero' && (
          <div style={sectionStyle}>
            <h3 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '20px' }}>Hero Section</h3>

            <label style={labelStyle}>Hero Inline Image (pill shape in title)</label>
            {formData.heroImage && (
              <img src={formData.heroImage.startsWith('http') ? formData.heroImage : `${import.meta.env.VITE_API_URL || 'http://localhost:5000'}${formData.heroImage}`} alt="Hero" style={imagePreviewStyle} />
            )}
            <input type="file" accept="image/*" onChange={(e) => handleImageUpload(e, 'heroImage')} style={{ marginBottom: '16px' }} />

            <label style={labelStyle}>Description</label>
            <textarea name="heroDescription" value={formData.heroDescription} onChange={handleChange} style={{ ...inputStyle, minHeight: '80px' }} />

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
              <div>
                <label style={labelStyle}>Button 1 Text</label>
                <input type="text" name="heroButton1Text" value={formData.heroButton1Text} onChange={handleChange} style={inputStyle} />
              </div>
              <div>
                <label style={labelStyle}>Button 2 Text</label>
                <input type="text" name="heroButton2Text" value={formData.heroButton2Text} onChange={handleChange} style={inputStyle} />
              </div>
            </div>

            <label style={labelStyle}>Instant Response Text</label>
            <input type="text" name="heroInstantText" value={formData.heroInstantText} onChange={handleChange} style={inputStyle} />
          </div>
        )}

        {/* Partners Section */}
        {activeSection === 'partners' && (
          <div style={sectionStyle}>
            <h3 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '20px' }}>Partner Brands Section</h3>

            <label style={labelStyle}>Partner Title</label>
            <textarea name="partnerTitle" value={formData.partnerTitle} onChange={handleChange} style={{ ...inputStyle, minHeight: '80px' }} />
          </div>
        )}

        {/* Experience Section */}
        {activeSection === 'experience' && (
          <div style={sectionStyle}>
            <h3 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '20px' }}>Experience Section</h3>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
              <div>
                <label style={labelStyle}>Title Part 1 (Italic)</label>
                <input type="text" name="experienceTitle1" value={formData.experienceTitle1} onChange={handleChange} style={inputStyle} />
              </div>
              <div>
                <label style={labelStyle}>Title Part 2</label>
                <input type="text" name="experienceTitle2" value={formData.experienceTitle2} onChange={handleChange} style={inputStyle} />
              </div>
              <div>
                <label style={labelStyle}>Title Part 3 (Italic)</label>
                <input type="text" name="experienceTitle3" value={formData.experienceTitle3} onChange={handleChange} style={inputStyle} />
              </div>
              <div>
                <label style={labelStyle}>Title Part 4</label>
                <input type="text" name="experienceTitle4" value={formData.experienceTitle4} onChange={handleChange} style={inputStyle} />
              </div>
            </div>

            <label style={labelStyle}>Description</label>
            <textarea name="experienceDescription" value={formData.experienceDescription} onChange={handleChange} style={{ ...inputStyle, minHeight: '80px' }} />
          </div>
        )}

        {/* Want More Section */}
        {activeSection === 'wantMore' && (
          <div style={sectionStyle}>
            <h3 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '20px' }}>Want To See More Section</h3>

            <label style={labelStyle}>Title</label>
            <input type="text" name="wantMoreTitle" value={formData.wantMoreTitle} onChange={handleChange} style={inputStyle} />

            <label style={labelStyle}>Button Text</label>
            <input type="text" name="wantMoreButtonText" value={formData.wantMoreButtonText} onChange={handleChange} style={inputStyle} />
          </div>
        )}

        {/* Real Numbers Section */}
        {activeSection === 'realNumbers' && (
          <div style={sectionStyle}>
            <h3 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '20px' }}>Real Numbers Section</h3>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
              <div>
                <label style={labelStyle}>Title (Italic)</label>
                <input type="text" name="realNumbersTitle" value={formData.realNumbersTitle} onChange={handleChange} style={inputStyle} />
              </div>
              <div>
                <label style={labelStyle}>Title (Normal)</label>
                <input type="text" name="realNumbersTitleNormal" value={formData.realNumbersTitleNormal} onChange={handleChange} style={inputStyle} />
              </div>
            </div>

            <h4 style={{ fontSize: '16px', fontWeight: 500, marginTop: '16px', marginBottom: '12px' }}>Stat 1</h4>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '16px' }}>
              <div>
                <label style={labelStyle}>Value</label>
                <input type="text" name="stat1Value" value={formData.stat1Value} onChange={handleChange} style={inputStyle} />
              </div>
              <div>
                <label style={labelStyle}>Label</label>
                <input type="text" name="stat1Label" value={formData.stat1Label} onChange={handleChange} style={inputStyle} />
              </div>
            </div>

            <h4 style={{ fontSize: '16px', fontWeight: 500, marginTop: '16px', marginBottom: '12px' }}>Stat 2</h4>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '16px' }}>
              <div>
                <label style={labelStyle}>Value</label>
                <input type="text" name="stat2Value" value={formData.stat2Value} onChange={handleChange} style={inputStyle} />
              </div>
              <div>
                <label style={labelStyle}>Label</label>
                <input type="text" name="stat2Label" value={formData.stat2Label} onChange={handleChange} style={inputStyle} />
              </div>
            </div>

            <h4 style={{ fontSize: '16px', fontWeight: 500, marginTop: '16px', marginBottom: '12px' }}>Stat 3</h4>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '16px' }}>
              <div>
                <label style={labelStyle}>Value</label>
                <input type="text" name="stat3Value" value={formData.stat3Value} onChange={handleChange} style={inputStyle} />
              </div>
              <div>
                <label style={labelStyle}>Label</label>
                <input type="text" name="stat3Label" value={formData.stat3Label} onChange={handleChange} style={inputStyle} />
              </div>
            </div>

            <h4 style={{ fontSize: '16px', fontWeight: 500, marginTop: '16px', marginBottom: '12px' }}>Stat 4</h4>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '16px' }}>
              <div>
                <label style={labelStyle}>Value</label>
                <input type="text" name="stat4Value" value={formData.stat4Value} onChange={handleChange} style={inputStyle} />
              </div>
              <div>
                <label style={labelStyle}>Label</label>
                <input type="text" name="stat4Label" value={formData.stat4Label} onChange={handleChange} style={inputStyle} />
              </div>
            </div>

            <h4 style={{ fontSize: '16px', fontWeight: 500, marginTop: '16px', marginBottom: '12px' }}>Stat 5 (with Image)</h4>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '16px' }}>
              <div>
                <label style={labelStyle}>Value</label>
                <input type="text" name="stat5Value" value={formData.stat5Value} onChange={handleChange} style={inputStyle} />
              </div>
              <div>
                <label style={labelStyle}>Label</label>
                <input type="text" name="stat5Label" value={formData.stat5Label} onChange={handleChange} style={inputStyle} />
              </div>
            </div>
            <label style={labelStyle}>Stat 5 Image</label>
            {formData.stat5Image && (
              <img src={formData.stat5Image.startsWith('http') ? formData.stat5Image : `${import.meta.env.VITE_API_URL || 'http://localhost:5000'}${formData.stat5Image}`} alt="Stat 5" style={{ ...imagePreviewStyle, width: '80px', height: '80px' }} />
            )}
            <input type="file" accept="image/*" onChange={(e) => handleImageUpload(e, 'stat5Image')} />
          </div>
        )}

        {/* Services Section */}
        {activeSection === 'services' && (
          <div style={sectionStyle}>
            <h3 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '20px' }}>Services Section</h3>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
              <div>
                <label style={labelStyle}>Title (Italic)</label>
                <input type="text" name="servicesTitle" value={formData.servicesTitle} onChange={handleChange} style={inputStyle} />
              </div>
              <div>
                <label style={labelStyle}>Title (Normal)</label>
                <input type="text" name="servicesTitleNormal" value={formData.servicesTitleNormal} onChange={handleChange} style={inputStyle} />
              </div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginTop: '16px' }}>
              <div>
                <label style={labelStyle}>CTA Button Text</label>
                <input type="text" name="ctaMidButtonText" value={formData.ctaMidButtonText} onChange={handleChange} style={inputStyle} />
              </div>
              <div>
                <label style={labelStyle}>Instant Response Text</label>
                <input type="text" name="ctaMidInstantText" value={formData.ctaMidInstantText} onChange={handleChange} style={inputStyle} />
              </div>
            </div>

            {[1, 2, 3].map((num) => (
              <div key={num} style={{ marginTop: '24px', padding: '16px', backgroundColor: '#F9F9F9', borderRadius: '8px' }}>
                <h4 style={{ fontSize: '16px', fontWeight: 500, marginBottom: '12px' }}>Service {num}</h4>
                <label style={labelStyle}>Title</label>
                <input type="text" name={`service${num}Title`} value={formData[`service${num}Title`]} onChange={handleChange} style={inputStyle} />
                <label style={labelStyle}>Description</label>
                <textarea name={`service${num}Description`} value={formData[`service${num}Description`]} onChange={handleChange} style={{ ...inputStyle, minHeight: '80px' }} />
                <label style={labelStyle}>Image</label>
                {formData[`service${num}Image`] && (
                  <img src={formData[`service${num}Image`].startsWith('http') ? formData[`service${num}Image`] : `${import.meta.env.VITE_API_URL || 'http://localhost:5000'}${formData[`service${num}Image`]}`} alt={`Service ${num}`} style={imagePreviewStyle} />
                )}
                <input type="file" accept="image/*" onChange={(e) => handleImageUpload(e, `service${num}Image`)} />
              </div>
            ))}
          </div>
        )}

        {/* Brands Section */}
        {activeSection === 'brands' && (
          <div style={sectionStyle}>
            <h3 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '20px' }}>Brands Section</h3>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '16px' }}>
              <div>
                <label style={labelStyle}>Title Start</label>
                <input type="text" name="brandsTitle" value={formData.brandsTitle} onChange={handleChange} style={inputStyle} />
              </div>
              <div>
                <label style={labelStyle}>Title Italic</label>
                <input type="text" name="brandsTitleItalic" value={formData.brandsTitleItalic} onChange={handleChange} style={inputStyle} />
              </div>
              <div>
                <label style={labelStyle}>Title End (Italic)</label>
                <input type="text" name="brandsTitleEnd" value={formData.brandsTitleEnd} onChange={handleChange} style={inputStyle} />
              </div>
            </div>

            <label style={labelStyle}>Description</label>
            <textarea name="brandsDescription" value={formData.brandsDescription} onChange={handleChange} style={{ ...inputStyle, minHeight: '80px' }} />

            {[1, 2, 3, 4].map((num) => (
              <div key={num} style={{ marginTop: '16px', padding: '16px', backgroundColor: '#F9F9F9', borderRadius: '8px' }}>
                <h4 style={{ fontSize: '16px', fontWeight: 500, marginBottom: '12px' }}>Accordion {num}</h4>
                <label style={labelStyle}>Title</label>
                <input type="text" name={`accordion${num}Title`} value={formData[`accordion${num}Title`]} onChange={handleChange} style={inputStyle} />
                <label style={labelStyle}>Items (comma-separated)</label>
                <input type="text" name={`accordion${num}Items`} value={formData[`accordion${num}Items`]} onChange={handleChange} style={inputStyle} placeholder="Item 1, Item 2, Item 3" />
              </div>
            ))}
          </div>
        )}

        {/* CTA Section */}
        {activeSection === 'cta' && (
          <div style={sectionStyle}>
            <h3 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '20px' }}>CTA Section</h3>

            <label style={labelStyle}>Heading</label>
            <input type="text" name="ctaHeading" value={formData.ctaHeading} onChange={handleChange} style={inputStyle} />

            <label style={labelStyle}>Description Line 1</label>
            <input type="text" name="ctaDescription1" value={formData.ctaDescription1} onChange={handleChange} style={inputStyle} />

            <label style={labelStyle}>Description Line 2</label>
            <input type="text" name="ctaDescription2" value={formData.ctaDescription2} onChange={handleChange} style={inputStyle} />

            <label style={labelStyle}>Description Line 3</label>
            <input type="text" name="ctaDescription3" value={formData.ctaDescription3} onChange={handleChange} style={inputStyle} />

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
              <div>
                <label style={labelStyle}>Button Text</label>
                <input type="text" name="ctaButtonText" value={formData.ctaButtonText} onChange={handleChange} style={inputStyle} />
              </div>
              <div>
                <label style={labelStyle}>Instant Response Text</label>
                <input type="text" name="ctaInstantText" value={formData.ctaInstantText} onChange={handleChange} style={inputStyle} />
              </div>
            </div>
          </div>
        )}

        {/* FAQ Section */}
        {activeSection === 'faq' && (
          <div style={sectionStyle}>
            <h3 style={{ fontSize: '18px', fontWeight: 600, marginBottom: '20px' }}>FAQ Section</h3>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
              <div>
                <label style={labelStyle}>Title (Italic)</label>
                <input type="text" name="faqTitle" value={formData.faqTitle} onChange={handleChange} style={inputStyle} />
              </div>
              <div>
                <label style={labelStyle}>Title (Normal)</label>
                <input type="text" name="faqTitleNormal" value={formData.faqTitleNormal} onChange={handleChange} style={inputStyle} />
              </div>
            </div>

            {[1, 2, 3, 4, 5].map((num) => (
              <div key={num} style={{ marginTop: '16px', padding: '16px', backgroundColor: '#F9F9F9', borderRadius: '8px' }}>
                <h4 style={{ fontSize: '16px', fontWeight: 500, marginBottom: '12px' }}>FAQ {num}</h4>
                <label style={labelStyle}>Question</label>
                <input type="text" name={`faq${num}Question`} value={formData[`faq${num}Question`]} onChange={handleChange} style={inputStyle} />
                <label style={labelStyle}>Answer</label>
                <textarea name={`faq${num}Answer`} value={formData[`faq${num}Answer`]} onChange={handleChange} style={{ ...inputStyle, minHeight: '80px' }} />
              </div>
            ))}

            <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: '16px', marginTop: '16px' }}>
              <div>
                <label style={labelStyle}>Contact Text</label>
                <input type="text" name="faqContactText" value={formData.faqContactText} onChange={handleChange} style={inputStyle} />
              </div>
              <div>
                <label style={labelStyle}>Contact Link Text</label>
                <input type="text" name="faqContactLink" value={formData.faqContactLink} onChange={handleChange} style={inputStyle} />
              </div>
            </div>
          </div>
        )}
      </form>
    </div>
  );
};

export default HomePageEditor;
