import { createContext, useContext, useState, useCallback, useEffect } from 'react';
import { pagesAPI } from '../services/api';

const PageEditorContext = createContext(null);

// Default values for pages (shown in admin panel when page hasn't been saved yet)
const pageDefaults = {
  home: {
    // Section Visibility (all visible by default)
    heroVisible: true,
    partnersVisible: true,
    experienceVisible: true,
    projectsVisible: true,
    wantMoreVisible: true,
    realNumbersVisible: true,
    servicesVisible: true,
    brandsVisible: true,
    ctaVisible: true,
    faqVisible: true,
  },
  landing: {
    // Section Visibility (all visible by default)
    topBannerVisible: true,
    heroVisible: true,
    trustedByVisible: true,
    portfolioVisible: true,
    statsVisible: true,
    hiddenCostVisible: true,
    familiarVisible: true,
    comparisonVisible: true,
    processVisible: true,
    valueVisible: true,
    testimonialsVisible: true,
    socialProofVisible: true,
    faqVisible: true,
    contactFormVisible: true,
    landingFooterVisible: true,
    // Top Banner
    bannerText: 'Egestas facilisi commodo in sapien integer ut',
    bannerEndDate: '2026-03-01 00:00',
    showBanner: 'yes',
    // Hero
    heroTitle: "We Build Shopify Websites That Don't Just Look Good —",
    heroTitleHighlight: 'They Sell.',
    heroDescription: "India's trusted Shopify agency delivering design, development, and conversion results you can count on.",
    heroButtonText: 'Get A Web Design Quote',
    heroButtonLink: '/home',
    stat1Value: '2-3 weeks',
    stat1Label: 'Average delivery',
    stat2Value: '$2M+',
    stat2Label: 'Revenue generated',
    stat3Value: '100%',
    stat3Label: 'Satisfaction rate',
    // Trusted By
    trustedByTitle: 'Trusted by leading brands and recognized by',
    badge1Text: 'Shopify Plus Partner',
    badge2Text: 'Featured on Forbes',
    badge3Text: 'Inc. 5000',
    badge4Text: 'Best Design Award',
    badge5Text: 'E-commerce Expert',
    review1Rating: '4.9',
    review1Source: 'on Google (127 reviews)',
    review2Rating: '4.9',
    review2Source: 'on Trustpilot (127 reviews)',
    review3Rating: '4.9',
    review3Source: 'on Clutch (127 reviews)',
    // Portfolio
    portfolioCategory: 'Fitness and Wellness',
    // Stats
    statsTitle: 'Real Numbers, Real Impact',
    statLive1Value: '$280,366',
    statLive1Label: 'Total Revenue Generated by our clients',
    statLive2Value: '261',
    statLive2Label: 'Stores Launched and counting',
    statLive3Value: '5.8%',
    statLive3Label: 'Average Conversion Rate vs 2.5% industry avg',
    statLive4Value: '4.9/5',
    statLive4Label: 'Client Satisfaction from 200+ reviews',
    // Hidden Cost
    hiddenCostTitle: 'The Hidden Cost of Cheap',
    hiddenCostTitleHighlight: 'Shopify Stores',
    painPoint1Title: 'Waiting 3-6 months for your store to launch',
    painPoint1Desc: 'Your competitors are already capturing your market share',
    painPoint1Stat: '73% of customers buy from the first store they find',
    painPoint2Title: 'Freelancers who disappear after the first payment',
    painPoint2Desc: 'Freelancers who disappear after the first payment',
    painPoint2Stat: '$8,500 average loss on failed freelance projects',
    painPoint3Title: 'Paying per revision or getting ghosted when you ask for changes',
    painPoint3Desc: 'Your vision stays in your head, never making it to the screen',
    painPoint3Stat: '67% of clients unhappy with "final" deliverables',
    painPoint4Title: "Beautiful designs that don't actually convert",
    painPoint4Desc: 'High traffic but no sales means burning money on ads',
    painPoint4Stat: 'Average e-commerce conversion rate is only 2.5-3%',
    // Familiar
    familiarTitle: 'it\'s because too many brands settle for "cheap" that ends',
    familiarTitleHighlight: 'up costing more later',
    familiarDescription: 'At GOTI, we do it right from the start — thoughtful design, solid development, and strategies backed by data. We build Shopify stores that earn trust and drive conversions from day one.',
    // Comparison
    col1Title: 'DIY with Templates',
    col1Subtitle: 'Your time is worth more than this',
    col1Items: '6-12 weeks of your time\nGeneric, cookie-cutter design\nNo conversion optimization\nTechnical headaches\nLooks like 1000 other stores\nNo support when issues arise',
    col2Title: 'GOTI Premium',
    col2Subtitle: 'Investment that pays for itself',
    col2Items: '2-3 week launch timeline\nConversion-focused design\nUnlimited revisions\nE-commerce psychology experts\n10-day money-back guarantee\n30 days post-launch support\nlorem ipsum dolae sitliw',
    col3Title: 'Cheap Freelancers',
    col3Subtitle: 'Cheap always costs more in the long run',
    col3Items: '3-6 month timeline\nCommunication nightmares\nQuestionable quality\nRevisions cost extra\nThey disappear after payment\nNo business understanding',
    // Process
    processTitle: 'Our Simple Process',
    processSubtitle: 'From concept to launch in 4 simple steps. No complexity, just results.',
    step1Title: 'Discovery Call',
    step1Desc: 'We start by understanding your brand, goals, and target audience. This 30-minute call sets the foundation for your perfect store.',
    step2Title: 'Design & Branding',
    step2Desc: 'Our designers create a stunning, conversion-optimized design that reflects your brand and appeals to your customers.',
    step3Title: 'Development',
    step3Desc: 'We bring the design to life on Shopify, ensuring every element is optimized for performance and conversions.',
    step4Title: 'Launch & Support',
    step4Desc: 'After your approval, we launch your store and provide ongoing support to ensure everything runs smoothly.',
    processCTAText: 'Claim Your Spot Now',
    // Value
    valueTitle: "Now Let's Talk About",
    valueTitleHighlight: "What You're Getting...",
    feature1: 'Custom Shopify Theme Development',
    feature1Desc: 'Unique design that converts',
    feature2: 'Responsive Mobile Optimization',
    feature2Desc: 'Perfect on every device',
    feature3: 'SEO Setup & Optimization',
    feature3Desc: 'Get found on Google',
    feature4: 'Product Page Templates',
    feature4Desc: '5 high-converting variations',
    feature5: 'Shopping Cart & Checkout Customization',
    feature5Desc: 'Reduce cart abandonment',
    feature6: '30 Days Post-Launch Support',
    feature6Desc: "We've got your back",
    worthText: 'All of these are worth ~ $5000',
    worthSubtext: 'other agencies charges.. $6000-$10000',
    payText: 'But with GOTI, you only pay',
    priceValue: '$1,200',
    priceDiscount: '70% Off',
    priceSubtext: 'One-time investment. Lifetime value.',
    priceCTAText: "Let's Make It Happen",
    guarantee1: '2-3 Week Launch',
    guarantee1Sub: 'Get to market fast',
    guarantee2: 'Unlimited Revisions',
    guarantee2Sub: "Until it's perfect",
    guarantee3: '10-Day Guarantee',
    guarantee3Sub: 'Risk-free promise',
    // Testimonials
    testimonialTitle: "Don't Just Take",
    testimonialTitleHighlight: 'Our Word For It',
    testimonialSubtitle: "Watch real store owners share their success stories. These aren't actors—they're actual clients who've transformed their businesses with GOTI.",
    testimonials: [
      {
        id: 1,
        quote1: 'Lorem ipsum dolor sit amet consectetur. Ullamcorper amet arcu quis elementum. Convallis purus mauris at in.',
        quote2: 'Pretium pharetra aliquam consequat duis ac risus vitae sollicitudin pharetra.',
        authorName: 'Reema Roy',
        authorRole: 'Head of Marketing, Company-name',
        authorImage: '',
        stat1Value: '+45%',
        stat1Label: 'AOV (Average Order Value)',
        stat2Value: '+24%',
        stat2Label: 'CTR (Click-through rate)',
        stat3Value: '+16%',
        stat3Label: 'Return-rate per customer',
      },
    ],
    // Social Proof
    reviewCount: '990+',
    reviewText: 'Join 200+ successful store owners',
    reviewSubtext: 'demo text goes here.',
    moreCount: '+195 more',
    // FAQ
    faqTitle: 'Frequently Asked Question',
    faq1Question: 'Lorem ipsum dolor sit amet consectetur?',
    faq1Answer: 'Lorem ipsum dolor sit amet consectetur. In faucibus aliquam turpis maurstibulum malesuada.',
    faq2Question: 'Lorem ipsum dolor sit amet consectetur?',
    faq2Answer: 'Lorem ipsum dolor sit amet consectetur.',
    faq3Question: 'In faucibus aliquam turpis maurstibulum malesuada.?',
    faq3Answer: 'Lorem ipsum dolor sit amet consectetur.',
    faq4Question: 'Lorem ipsum dolor sit amet consectetur?',
    faq4Answer: 'Lorem ipsum dolor sit amet consectetur.',
    faq5Question: 'Lorem ipsum dolor sit amet consectetur. In faucibus aliquam turpis mauris convallis vestibulum malesuada.?',
    faq5Answer: 'Lorem ipsum dolor sit amet consectetur.',
    faq6Question: 'Lorem ipsum dolor sit amet consectetur?',
    faq6Answer: 'Lorem ipsum dolor sit amet consectetur.',
    faq7Question: 'Lorem ipsum dolor sit amet consectetur?',
    faq7Answer: 'Lorem ipsum dolor sit amet consectetur.',
    // Contact Form
    formTitle: 'Have More Question?',
    formSubtitle: 'Book A Call',
    formTags: 'Branding, Packaging, Website',
    formButtonText: 'Submit Now',
    formResponseText: 'Get Instant Response',
    // Landing Footer
    copyrightText: 'Copyright© 2025 GOTI.DESIGN. All rights reserved.',
    siteUseLink: 'Site Use',
  },
  'landing-page-2': {
    // Section Visibility (all visible by default)
    headerVisible: true,
    heroVisible: true,
    guaranteesVisible: true,
    clientsVisible: true,
    pricingVisible: true,
    callNowVisible: true,
    contactFormVisible: true,
    footerVisible: true,
    // Header
    logoText: 'goti',
    // Hero Section
    heroTitle: 'Your Shopify Website Design Agency',
    heroDescription: "We specialize in Shopify design and development.\nLet's design, optimize, and launch your Shopify store with guaranteed results -\nor you don't pay.",
    heroButtonText: 'See Price',
    // Guarantees
    guarantee1Title: '10-Day Satisfaction Guarantee',
    guarantee1Text: "— Get a full refund if you're not happy, no questions asked.",
    guarantee2Title: 'Launch your E-commerce business in weeks,',
    guarantee2Highlight: 'not months.',
    guarantee3Title: 'Unlimited revisions',
    guarantee3Text: 'until your website looks exactly how you want it.',
    // Clients
    clientsTitle: 'Our Shopify Clients',
    clientName1: '#basanti',
    clientName2: 'baharasee',
    clientName3: 'NOOR',
    clientName4: 'knotty rope',
    // Pricing
    pricingTitle: 'Shopify Design Plans.',
    pricingSubtitle: "Choose a plan that's right for you...",
    plan1Label: 'Popular Plan',
    plan1Price: '₹00,000/-',
    plan1Subtitle: 'One request at a time. Pause or cancel anytime.',
    plan1Features: 'Complete Shopify Theme Setup & Customization\nProduct Upload (Up to 300 Products)\nPayment Gateway & Shipping Setup\nFully Mobile-Optimized Design\nFast-Loading, SEO-Friendly Pages\nGoogle Analytics Integration\nGoogle & Meta (Facebook/Instagram) Ads Setup\n3 Shopify Training Sessions',
    plan2Price: '₹00,000/-',
    plan2Subtitle: 'Two requests at a time. Pause or cancel anytime.',
    plan2Features: 'Custom Store Design in Figma Before Development\nUnlimited Product Listings\nCustom Upsell & Cross-Sell Flows\nTwo Extra Landing Pages for Your Hero Products\nEmail Marketing Integration & Flow Setup\nOn-Page SEO Optimization for Main Pages\nConversion Audit After Launch (30 Days Later)\nEverything Included in the MVP Plan',
    // Call Now CTA
    ctaTitle: "Not sure what's right for you? Let's figure it out together.",
    ctaDescription: "Want to learn more about how we work or what's best for your store? We'll walk you through everything step by step.",
    ctaButtonText: 'Call Now',
    ctaPhoneNumber: '+919876543210',
    // Contact Form
    formTitle: "Let's Build Your Shopify Store — The Right Way.",
    formDescription: "Get expert advice tailored to your brand. Whether you're starting fresh or redesigning, we'll guide you with a clear plan — no tech stress, no fluff.",
    formButtonText: 'Book A Call',
    formResponseText: '*Get Instant Response*',
    showShopifyBadge: 'yes',
    formNamePlaceholder: 'Your name',
    formEmailPlaceholder: 'Your email',
    formPhonePlaceholder: 'Your contact number',
    successTitle: 'Thank you!',
    successMessage: "We'll get back to you within 24 hours.",
    // Footer
    footerText: 'Thanks for visiting',
    copyrightText: '© Goti 2025. All rights reserved.',
  },
  about: {
    // Section Visibility (all visible by default)
    heroVisible: true,
    youDontNeedVisible: true,
    tenMindsVisible: true,
    testimonialHeadingVisible: true,
    ctaVisible: true,
    // Hero Section
    heroTitle1: 'What matters',
    heroTitle1Italic: 'tomorrow,',
    heroTitle2: 'We design',
    heroTitle2Italic: 'today.',
    designBoxSubtitle: "Design isn't decoration.",
    designBoxLine1: "It's clarity.",
    designBoxLine2: "It's strategy.",
    designBoxLine3: "It's momentum.",
    designBoxLinkText: 'Explore Our Work',
    // You don't need section
    sectionTitle: 'You don\'t need "70+" people.',
    sectionSubtitle: 'You need the right 10.',
    sectionDescription: 'At GOTI, we\'ve assembled a curated team of senior designers, strategists, and developers who work exclusively on a handful of projects at a time. No bloat. No endless meetings. No getting lost in the shuffle.',
    // 10 Minds Section
    mindsTitle: '10 Minds. Built Different.',
    mindsDescription: 'GOTI is a name that sparks curiosity and stays with you. Beyond its simplicity, it represents strategy, unity, and bold movement in everything we build.',
    // Testimonial Heading
    testimonialTextItalic: 'GOTI',
    testimonialTextNormal: 'is a name that sparks curiosity and stays with you. Beyond its simplicity, it represents strategy, unity, and bold movement in everything we build.',
    clientLabelItalic: 'Look',
    clientLabelNormal: 'what our client said..',
    // CTA Section
    ctaTitle: 'Ready to start a project?',
    ctaDescription: 'We combine strategy, design, and performance to create experiences that convert.',
    ctaButtonText: 'Schedule Call',
  },
  work: {
    // Section Visibility (all visible by default)
    heroVisible: true,
    ctaVisible: true,
  },
  contact: {
    // Section Visibility (all visible by default)
    heroVisible: true,
    formVisible: true,
  },
};

export const PageEditorProvider = ({ children, pageName }) => {
  const [formData, setFormData] = useState({});
  const [originalData, setOriginalData] = useState({});
  const [selectedSection, setSelectedSection] = useState(null);
  const [isDirty, setIsDirty] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);

  // Load page data
  useEffect(() => {
    const fetchPageData = async () => {
      if (!pageName) return;

      setIsLoading(true);
      const defaults = pageDefaults[pageName] || {};

      try {
        const response = await pagesAPI.getOne(pageName);
        const content = response.data.data?.content || {};
        // Merge defaults with saved content (saved content takes priority)
        const mergedContent = { ...defaults, ...content };
        setFormData(mergedContent);
        setOriginalData(mergedContent);
        setError(null);
      } catch (err) {
        // 404 means page doesn't exist yet - use defaults
        if (err.response?.status === 404) {
          console.log(`Page "${pageName}" not created yet, starting with defaults`);
          setFormData(defaults);
          setOriginalData(defaults);
          setError(null);
        } else {
          console.error('Error fetching page data:', err);
          setError('Failed to load page data');
        }
      } finally {
        setIsLoading(false);
      }
    };

    fetchPageData();
  }, [pageName]);

  // Check for dirty state
  useEffect(() => {
    // Compare current formData with originalData
    const hasChanges = JSON.stringify(formData) !== JSON.stringify(originalData);
    setIsDirty(hasChanges);
  }, [formData, originalData]);

  // Update a single field
  const updateField = useCallback((fieldKey, value) => {
    setFormData(prev => ({
      ...prev,
      [fieldKey]: value
    }));
  }, []);

  // Update multiple fields at once
  const updateFields = useCallback((updates) => {
    setFormData(prev => ({
      ...prev,
      ...updates
    }));
  }, []);

  // Update array field (add/remove/update item)
  const updateArrayField = useCallback((fieldKey, newArray) => {
    setFormData(prev => ({
      ...prev,
      [fieldKey]: newArray
    }));
  }, []);

  // Select a section
  const selectSection = useCallback((sectionId) => {
    setSelectedSection(sectionId);
  }, []);

  // Save changes
  const saveChanges = useCallback(async () => {
    if (!pageName) return;

    setIsSaving(true);
    try {
      await pagesAPI.update(pageName, { content: formData });
      setOriginalData(formData);
      setIsDirty(false);
      return { success: true };
    } catch (err) {
      console.error('Error saving page:', err);
      return { success: false, error: err.message };
    } finally {
      setIsSaving(false);
    }
  }, [pageName, formData]);

  // Reset to original data
  const resetChanges = useCallback(() => {
    setFormData(originalData);
    setIsDirty(false);
  }, [originalData]);

  // Warn before leaving with unsaved changes
  useEffect(() => {
    const handleBeforeUnload = (e) => {
      if (isDirty) {
        e.preventDefault();
        e.returnValue = '';
      }
    };

    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => window.removeEventListener('beforeunload', handleBeforeUnload);
  }, [isDirty]);

  const value = {
    pageName,
    formData,
    selectedSection,
    isDirty,
    isSaving,
    isLoading,
    error,
    updateField,
    updateFields,
    updateArrayField,
    selectSection,
    saveChanges,
    resetChanges,
  };

  return (
    <PageEditorContext.Provider value={value}>
      {children}
    </PageEditorContext.Provider>
  );
};

export const usePageEditor = () => {
  const context = useContext(PageEditorContext);
  if (!context) {
    throw new Error('usePageEditor must be used within a PageEditorProvider');
  }
  return context;
};

export default PageEditorContext;
